package com.hndl.mobileplatform.model;

public class Dlfilesmanager {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dlFilesManager.fileid
     *
     * @mbggenerated Fri Jul 03 18:29:32 CST 2015
     */
    private String fileid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dlFilesManager.filename
     *
     * @mbggenerated Fri Jul 03 18:29:32 CST 2015
     */
    private String filename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dlFilesManager.filepath
     *
     * @mbggenerated Fri Jul 03 18:29:32 CST 2015
     */
    private String filepath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dlFilesManager.filesize
     *
     * @mbggenerated Fri Jul 03 18:29:32 CST 2015
     */
    private String filesize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dlFilesManager.createtime
     *
     * @mbggenerated Fri Jul 03 18:29:32 CST 2015
     */
    private String createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dlFilesManager.createid
     *
     * @mbggenerated Fri Jul 03 18:29:32 CST 2015
     */
    private String createid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dlFilesManager.userorroom
     *
     * @mbggenerated Fri Jul 03 18:29:32 CST 2015
     */
    private String userorroom;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dlFilesManager.type
     *
     * @mbggenerated Fri Jul 03 18:29:32 CST 2015
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dlFilesManager.userorroomid
     *
     * @mbggenerated Fri Jul 03 18:29:32 CST 2015
     */
    private String userorroomid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dlFilesManager.bz5
     *
     * @mbggenerated Fri Jul 03 18:29:32 CST 2015
     */
    private String bz5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dlFilesManager.bz4
     *
     * @mbggenerated Fri Jul 03 18:29:32 CST 2015
     */
    private String bz4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dlFilesManager.bz3
     *
     * @mbggenerated Fri Jul 03 18:29:32 CST 2015
     */
    private String bz3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dlFilesManager.bz2
     *
     * @mbggenerated Fri Jul 03 18:29:32 CST 2015
     */
    private String bz2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dlFilesManager.bz1
     *
     * @mbggenerated Fri Jul 03 18:29:32 CST 2015
     */
    private String bz1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dlFilesManager.spaceid
     *
     * @mbggenerated Fri Jul 03 18:29:32 CST 2015
     */
    private String spaceid;

    //上传资料人只做显示使用
    private String  person;
    
    
	//前台展示(所属部门)
	private String department;
    
    
    public String getPerson() {
		return person;
	}

	public void setPerson(String person) {
		this.person = person;
	}

	public String getDepartment() {
		return department;
	}

	public void setDepartment(String department) {
		this.department = department;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dlFilesManager.fileid
     *
     * @return the value of dlFilesManager.fileid
     *
     * @mbggenerated Fri Jul 03 18:29:32 CST 2015
     */
    public String getFileid() {
        return fileid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dlFilesManager.fileid
     *
     * @param fileid the value for dlFilesManager.fileid
     *
     * @mbggenerated Fri Jul 03 18:29:32 CST 2015
     */
    public void setFileid(String fileid) {
        this.fileid = fileid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dlFilesManager.filename
     *
     * @return the value of dlFilesManager.filename
     *
     * @mbggenerated Fri Jul 03 18:29:32 CST 2015
     */
    public String getFilename() {
        return filename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dlFilesManager.filename
     *
     * @param filename the value for dlFilesManager.filename
     *
     * @mbggenerated Fri Jul 03 18:29:32 CST 2015
     */
    public void setFilename(String filename) {
        this.filename = filename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dlFilesManager.filepath
     *
     * @return the value of dlFilesManager.filepath
     *
     * @mbggenerated Fri Jul 03 18:29:32 CST 2015
     */
    public String getFilepath() {
        return filepath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dlFilesManager.filepath
     *
     * @param filepath the value for dlFilesManager.filepath
     *
     * @mbggenerated Fri Jul 03 18:29:32 CST 2015
     */
    public void setFilepath(String filepath) {
        this.filepath = filepath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dlFilesManager.filesize
     *
     * @return the value of dlFilesManager.filesize
     *
     * @mbggenerated Fri Jul 03 18:29:32 CST 2015
     */
    public String getFilesize() {
        return filesize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dlFilesManager.filesize
     *
     * @param filesize the value for dlFilesManager.filesize
     *
     * @mbggenerated Fri Jul 03 18:29:32 CST 2015
     */
    public void setFilesize(String filesize) {
        this.filesize = filesize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dlFilesManager.createtime
     *
     * @return the value of dlFilesManager.createtime
     *
     * @mbggenerated Fri Jul 03 18:29:32 CST 2015
     */
    public String getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dlFilesManager.createtime
     *
     * @param createtime the value for dlFilesManager.createtime
     *
     * @mbggenerated Fri Jul 03 18:29:32 CST 2015
     */
    public void setCreatetime(String createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dlFilesManager.createid
     *
     * @return the value of dlFilesManager.createid
     *
     * @mbggenerated Fri Jul 03 18:29:32 CST 2015
     */
    public String getCreateid() {
        return createid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dlFilesManager.createid
     *
     * @param createid the value for dlFilesManager.createid
     *
     * @mbggenerated Fri Jul 03 18:29:32 CST 2015
     */
    public void setCreateid(String createid) {
        this.createid = createid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dlFilesManager.userorroom
     *
     * @return the value of dlFilesManager.userorroom
     *
     * @mbggenerated Fri Jul 03 18:29:32 CST 2015
     */
    public String getUserorroom() {
        return userorroom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dlFilesManager.userorroom
     *
     * @param userorroom the value for dlFilesManager.userorroom
     *
     * @mbggenerated Fri Jul 03 18:29:32 CST 2015
     */
    public void setUserorroom(String userorroom) {
        this.userorroom = userorroom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dlFilesManager.type
     *
     * @return the value of dlFilesManager.type
     *
     * @mbggenerated Fri Jul 03 18:29:32 CST 2015
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dlFilesManager.type
     *
     * @param type the value for dlFilesManager.type
     *
     * @mbggenerated Fri Jul 03 18:29:32 CST 2015
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dlFilesManager.userorroomid
     *
     * @return the value of dlFilesManager.userorroomid
     *
     * @mbggenerated Fri Jul 03 18:29:32 CST 2015
     */
    public String getUserorroomid() {
        return userorroomid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dlFilesManager.userorroomid
     *
     * @param userorroomid the value for dlFilesManager.userorroomid
     *
     * @mbggenerated Fri Jul 03 18:29:32 CST 2015
     */
    public void setUserorroomid(String userorroomid) {
        this.userorroomid = userorroomid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dlFilesManager.bz5
     *
     * @return the value of dlFilesManager.bz5
     *
     * @mbggenerated Fri Jul 03 18:29:32 CST 2015
     */
    public String getBz5() {
        return bz5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dlFilesManager.bz5
     *
     * @param bz5 the value for dlFilesManager.bz5
     *
     * @mbggenerated Fri Jul 03 18:29:32 CST 2015
     */
    public void setBz5(String bz5) {
        this.bz5 = bz5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dlFilesManager.bz4
     *
     * @return the value of dlFilesManager.bz4
     *
     * @mbggenerated Fri Jul 03 18:29:32 CST 2015
     */
    public String getBz4() {
        return bz4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dlFilesManager.bz4
     *
     * @param bz4 the value for dlFilesManager.bz4
     *
     * @mbggenerated Fri Jul 03 18:29:32 CST 2015
     */
    public void setBz4(String bz4) {
        this.bz4 = bz4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dlFilesManager.bz3
     *
     * @return the value of dlFilesManager.bz3
     *
     * @mbggenerated Fri Jul 03 18:29:32 CST 2015
     */
    public String getBz3() {
        return bz3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dlFilesManager.bz3
     *
     * @param bz3 the value for dlFilesManager.bz3
     *
     * @mbggenerated Fri Jul 03 18:29:32 CST 2015
     */
    public void setBz3(String bz3) {
        this.bz3 = bz3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dlFilesManager.bz2
     *
     * @return the value of dlFilesManager.bz2
     *
     * @mbggenerated Fri Jul 03 18:29:32 CST 2015
     */
    public String getBz2() {
        return bz2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dlFilesManager.bz2
     *
     * @param bz2 the value for dlFilesManager.bz2
     *
     * @mbggenerated Fri Jul 03 18:29:32 CST 2015
     */
    public void setBz2(String bz2) {
        this.bz2 = bz2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dlFilesManager.bz1
     *
     * @return the value of dlFilesManager.bz1
     *
     * @mbggenerated Fri Jul 03 18:29:32 CST 2015
     */
    public String getBz1() {
        return bz1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dlFilesManager.bz1
     *
     * @param bz1 the value for dlFilesManager.bz1
     *
     * @mbggenerated Fri Jul 03 18:29:32 CST 2015
     */
    public void setBz1(String bz1) {
        this.bz1 = bz1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dlFilesManager.spaceid
     *
     * @return the value of dlFilesManager.spaceid
     *
     * @mbggenerated Fri Jul 03 18:29:32 CST 2015
     */
    public String getSpaceid() {
        return spaceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dlFilesManager.spaceid
     *
     * @param spaceid the value for dlFilesManager.spaceid
     *
     * @mbggenerated Fri Jul 03 18:29:32 CST 2015
     */
    public void setSpaceid(String spaceid) {
        this.spaceid = spaceid;
    }
}