package com.hndl.mobileplatform.model;

public class Dlnoticfile {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dlNoticFile.id
     *
     * @mbggenerated Thu Jul 16 17:56:52 CST 2015
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dlNoticFile.infoid
     *
     * @mbggenerated Thu Jul 16 17:56:52 CST 2015
     */
    private String infoid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dlNoticFile.filename
     *
     * @mbggenerated Thu Jul 16 17:56:52 CST 2015
     */
    private String filename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dlNoticFile.filepath
     *
     * @mbggenerated Thu Jul 16 17:56:52 CST 2015
     */
    private String filepath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dlNoticFile.time
     *
     * @mbggenerated Thu Jul 16 17:56:52 CST 2015
     */
    private String time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dlNoticFile.bz1
     *
     * @mbggenerated Thu Jul 16 17:56:52 CST 2015
     */
    private String bz1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dlNoticFile.bz2
     *
     * @mbggenerated Thu Jul 16 17:56:52 CST 2015
     */
    private String bz2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dlNoticFile.bz3
     *
     * @mbggenerated Thu Jul 16 17:56:52 CST 2015
     */
    private String bz3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dlNoticFile.bz4
     *
     * @mbggenerated Thu Jul 16 17:56:52 CST 2015
     */
    private String bz4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dlNoticFile.bz5
     *
     * @mbggenerated Thu Jul 16 17:56:52 CST 2015
     */
    private String bz5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dlNoticFile.size
     *
     * @mbggenerated Thu Jul 16 17:56:52 CST 2015
     */
    private String size;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dlNoticFile.id
     *
     * @return the value of dlNoticFile.id
     *
     * @mbggenerated Thu Jul 16 17:56:52 CST 2015
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dlNoticFile.id
     *
     * @param id the value for dlNoticFile.id
     *
     * @mbggenerated Thu Jul 16 17:56:52 CST 2015
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dlNoticFile.infoid
     *
     * @return the value of dlNoticFile.infoid
     *
     * @mbggenerated Thu Jul 16 17:56:52 CST 2015
     */
    public String getInfoid() {
        return infoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dlNoticFile.infoid
     *
     * @param infoid the value for dlNoticFile.infoid
     *
     * @mbggenerated Thu Jul 16 17:56:52 CST 2015
     */
    public void setInfoid(String infoid) {
        this.infoid = infoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dlNoticFile.filename
     *
     * @return the value of dlNoticFile.filename
     *
     * @mbggenerated Thu Jul 16 17:56:52 CST 2015
     */
    public String getFilename() {
        return filename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dlNoticFile.filename
     *
     * @param filename the value for dlNoticFile.filename
     *
     * @mbggenerated Thu Jul 16 17:56:52 CST 2015
     */
    public void setFilename(String filename) {
        this.filename = filename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dlNoticFile.filepath
     *
     * @return the value of dlNoticFile.filepath
     *
     * @mbggenerated Thu Jul 16 17:56:52 CST 2015
     */
    public String getFilepath() {
        return filepath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dlNoticFile.filepath
     *
     * @param filepath the value for dlNoticFile.filepath
     *
     * @mbggenerated Thu Jul 16 17:56:52 CST 2015
     */
    public void setFilepath(String filepath) {
        this.filepath = filepath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dlNoticFile.time
     *
     * @return the value of dlNoticFile.time
     *
     * @mbggenerated Thu Jul 16 17:56:52 CST 2015
     */
    public String getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dlNoticFile.time
     *
     * @param time the value for dlNoticFile.time
     *
     * @mbggenerated Thu Jul 16 17:56:52 CST 2015
     */
    public void setTime(String time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dlNoticFile.bz1
     *
     * @return the value of dlNoticFile.bz1
     *
     * @mbggenerated Thu Jul 16 17:56:52 CST 2015
     */
    public String getBz1() {
        return bz1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dlNoticFile.bz1
     *
     * @param bz1 the value for dlNoticFile.bz1
     *
     * @mbggenerated Thu Jul 16 17:56:52 CST 2015
     */
    public void setBz1(String bz1) {
        this.bz1 = bz1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dlNoticFile.bz2
     *
     * @return the value of dlNoticFile.bz2
     *
     * @mbggenerated Thu Jul 16 17:56:52 CST 2015
     */
    public String getBz2() {
        return bz2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dlNoticFile.bz2
     *
     * @param bz2 the value for dlNoticFile.bz2
     *
     * @mbggenerated Thu Jul 16 17:56:52 CST 2015
     */
    public void setBz2(String bz2) {
        this.bz2 = bz2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dlNoticFile.bz3
     *
     * @return the value of dlNoticFile.bz3
     *
     * @mbggenerated Thu Jul 16 17:56:52 CST 2015
     */
    public String getBz3() {
        return bz3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dlNoticFile.bz3
     *
     * @param bz3 the value for dlNoticFile.bz3
     *
     * @mbggenerated Thu Jul 16 17:56:52 CST 2015
     */
    public void setBz3(String bz3) {
        this.bz3 = bz3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dlNoticFile.bz4
     *
     * @return the value of dlNoticFile.bz4
     *
     * @mbggenerated Thu Jul 16 17:56:52 CST 2015
     */
    public String getBz4() {
        return bz4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dlNoticFile.bz4
     *
     * @param bz4 the value for dlNoticFile.bz4
     *
     * @mbggenerated Thu Jul 16 17:56:52 CST 2015
     */
    public void setBz4(String bz4) {
        this.bz4 = bz4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dlNoticFile.bz5
     *
     * @return the value of dlNoticFile.bz5
     *
     * @mbggenerated Thu Jul 16 17:56:52 CST 2015
     */
    public String getBz5() {
        return bz5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dlNoticFile.bz5
     *
     * @param bz5 the value for dlNoticFile.bz5
     *
     * @mbggenerated Thu Jul 16 17:56:52 CST 2015
     */
    public void setBz5(String bz5) {
        this.bz5 = bz5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dlNoticFile.size
     *
     * @return the value of dlNoticFile.size
     *
     * @mbggenerated Thu Jul 16 17:56:52 CST 2015
     */
    public String getSize() {
        return size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dlNoticFile.size
     *
     * @param size the value for dlNoticFile.size
     *
     * @mbggenerated Thu Jul 16 17:56:52 CST 2015
     */
    public void setSize(String size) {
        this.size = size;
    }
}