package com.hndl.mobileplatform.model;

public class Dlnoticeperson {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dlNoticePerson.id
     *
     * @mbggenerated Wed Jul 22 10:18:43 CST 2015
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dlNoticePerson.infoid
     *
     * @mbggenerated Wed Jul 22 10:18:43 CST 2015
     */
    private String infoid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dlNoticePerson.name
     *
     * @mbggenerated Wed Jul 22 10:18:43 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dlNoticePerson.type
     *
     * @mbggenerated Wed Jul 22 10:18:43 CST 2015
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dlNoticePerson.accepttime
     *
     * @mbggenerated Wed Jul 22 10:18:43 CST 2015
     */
    private String accepttime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dlNoticePerson.checktime
     *
     * @mbggenerated Wed Jul 22 10:18:43 CST 2015
     */
    private String checktime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dlNoticePerson.bz1
     *
     * @mbggenerated Wed Jul 22 10:18:43 CST 2015
     */
    private String bz1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dlNoticePerson.bz2
     *
     * @mbggenerated Wed Jul 22 10:18:43 CST 2015
     */
    private String bz2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dlNoticePerson.bz3
     *
     * @mbggenerated Wed Jul 22 10:18:43 CST 2015
     */
    private String bz3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dlNoticePerson.bz6
     *
     * @mbggenerated Wed Jul 22 10:18:43 CST 2015
     */
    private String bz6;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dlNoticePerson.bz7
     *
     * @mbggenerated Wed Jul 22 10:18:43 CST 2015
     */
    private String bz7;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dlNoticePerson.personid
     *
     * @mbggenerated Wed Jul 22 10:18:43 CST 2015
     */
    private String personid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dlNoticePerson.username
     *
     * @mbggenerated Wed Jul 22 10:18:43 CST 2015
     */
    private String username;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dlNoticePerson.id
     *
     * @return the value of dlNoticePerson.id
     *
     * @mbggenerated Wed Jul 22 10:18:43 CST 2015
     */
    
    
  //前台展示(所属部门)
  	private String department;
  	private String duty;//职务
  	private String age;//年龄
  	private String telephone;//手机
	private String officephone; //办公电话
	private String userQQ;//qq
	//查看状态
	private String  state;
	//查看性别
	private String  usersex;
    
    public String getUsersex() {
		return usersex;
	}

	public void setUsersex(String usersex) {
		this.usersex = usersex;
	}

	public String getState() {
		return state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public String getDepartment() {
		return department;
	}

	public void setDepartment(String department) {
		this.department = department;
	}

	public String getDuty() {
		return duty;
	}

	public void setDuty(String duty) {
		this.duty = duty;
	}

	public String getAge() {
		return age;
	}

	public void setAge(String age) {
		this.age = age;
	}

	public String getTelephone() {
		return telephone;
	}

	public void setTelephone(String telephone) {
		this.telephone = telephone;
	}

	public String getOfficephone() {
		return officephone;
	}

	public void setOfficephone(String officephone) {
		this.officephone = officephone;
	}

	public String getUserQQ() {
		return userQQ;
	}

	public void setUserQQ(String userQQ) {
		this.userQQ = userQQ;
	}

	public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dlNoticePerson.id
     *
     * @param id the value for dlNoticePerson.id
     *
     * @mbggenerated Wed Jul 22 10:18:43 CST 2015
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dlNoticePerson.infoid
     *
     * @return the value of dlNoticePerson.infoid
     *
     * @mbggenerated Wed Jul 22 10:18:43 CST 2015
     */
    public String getInfoid() {
        return infoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dlNoticePerson.infoid
     *
     * @param infoid the value for dlNoticePerson.infoid
     *
     * @mbggenerated Wed Jul 22 10:18:43 CST 2015
     */
    public void setInfoid(String infoid) {
        this.infoid = infoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dlNoticePerson.name
     *
     * @return the value of dlNoticePerson.name
     *
     * @mbggenerated Wed Jul 22 10:18:43 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dlNoticePerson.name
     *
     * @param name the value for dlNoticePerson.name
     *
     * @mbggenerated Wed Jul 22 10:18:43 CST 2015
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dlNoticePerson.type
     *
     * @return the value of dlNoticePerson.type
     *
     * @mbggenerated Wed Jul 22 10:18:43 CST 2015
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dlNoticePerson.type
     *
     * @param type the value for dlNoticePerson.type
     *
     * @mbggenerated Wed Jul 22 10:18:43 CST 2015
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dlNoticePerson.accepttime
     *
     * @return the value of dlNoticePerson.accepttime
     *
     * @mbggenerated Wed Jul 22 10:18:43 CST 2015
     */
    public String getAccepttime() {
        return accepttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dlNoticePerson.accepttime
     *
     * @param accepttime the value for dlNoticePerson.accepttime
     *
     * @mbggenerated Wed Jul 22 10:18:43 CST 2015
     */
    public void setAccepttime(String accepttime) {
        this.accepttime = accepttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dlNoticePerson.checktime
     *
     * @return the value of dlNoticePerson.checktime
     *
     * @mbggenerated Wed Jul 22 10:18:43 CST 2015
     */
    public String getChecktime() {
        return checktime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dlNoticePerson.checktime
     *
     * @param checktime the value for dlNoticePerson.checktime
     *
     * @mbggenerated Wed Jul 22 10:18:43 CST 2015
     */
    public void setChecktime(String checktime) {
        this.checktime = checktime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dlNoticePerson.bz1
     *
     * @return the value of dlNoticePerson.bz1
     *
     * @mbggenerated Wed Jul 22 10:18:43 CST 2015
     */
    public String getBz1() {
        return bz1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dlNoticePerson.bz1
     *
     * @param bz1 the value for dlNoticePerson.bz1
     *
     * @mbggenerated Wed Jul 22 10:18:43 CST 2015
     */
    public void setBz1(String bz1) {
        this.bz1 = bz1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dlNoticePerson.bz2
     *
     * @return the value of dlNoticePerson.bz2
     *
     * @mbggenerated Wed Jul 22 10:18:43 CST 2015
     */
    public String getBz2() {
        return bz2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dlNoticePerson.bz2
     *
     * @param bz2 the value for dlNoticePerson.bz2
     *
     * @mbggenerated Wed Jul 22 10:18:43 CST 2015
     */
    public void setBz2(String bz2) {
        this.bz2 = bz2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dlNoticePerson.bz3
     *
     * @return the value of dlNoticePerson.bz3
     *
     * @mbggenerated Wed Jul 22 10:18:43 CST 2015
     */
    public String getBz3() {
        return bz3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dlNoticePerson.bz3
     *
     * @param bz3 the value for dlNoticePerson.bz3
     *
     * @mbggenerated Wed Jul 22 10:18:43 CST 2015
     */
    public void setBz3(String bz3) {
        this.bz3 = bz3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dlNoticePerson.bz6
     *
     * @return the value of dlNoticePerson.bz6
     *
     * @mbggenerated Wed Jul 22 10:18:43 CST 2015
     */
    public String getBz6() {
        return bz6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dlNoticePerson.bz6
     *
     * @param bz6 the value for dlNoticePerson.bz6
     *
     * @mbggenerated Wed Jul 22 10:18:43 CST 2015
     */
    public void setBz6(String bz6) {
        this.bz6 = bz6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dlNoticePerson.bz7
     *
     * @return the value of dlNoticePerson.bz7
     *
     * @mbggenerated Wed Jul 22 10:18:43 CST 2015
     */
    public String getBz7() {
        return bz7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dlNoticePerson.bz7
     *
     * @param bz7 the value for dlNoticePerson.bz7
     *
     * @mbggenerated Wed Jul 22 10:18:43 CST 2015
     */
    public void setBz7(String bz7) {
        this.bz7 = bz7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dlNoticePerson.personid
     *
     * @return the value of dlNoticePerson.personid
     *
     * @mbggenerated Wed Jul 22 10:18:43 CST 2015
     */
    public String getPersonid() {
        return personid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dlNoticePerson.personid
     *
     * @param personid the value for dlNoticePerson.personid
     *
     * @mbggenerated Wed Jul 22 10:18:43 CST 2015
     */
    public void setPersonid(String personid) {
        this.personid = personid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dlNoticePerson.username
     *
     * @return the value of dlNoticePerson.username
     *
     * @mbggenerated Wed Jul 22 10:18:43 CST 2015
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dlNoticePerson.username
     *
     * @param username the value for dlNoticePerson.username
     *
     * @mbggenerated Wed Jul 22 10:18:43 CST 2015
     */
    public void setUsername(String username) {
        this.username = username;
    }
}