package com.hndl.mobileplatform.model;

public class DlroompostmessageWithBLOBs extends Dlroompostmessage {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dlRoomPostMessage.content
     *
     * @mbggenerated Thu Jul 16 17:57:54 CST 2015
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dlRoomPostMessage.content_type
     *
     * @mbggenerated Thu Jul 16 17:57:54 CST 2015
     */
    private String contentType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dlRoomPostMessage.content
     *
     * @return the value of dlRoomPostMessage.content
     *
     * @mbggenerated Thu Jul 16 17:57:54 CST 2015
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dlRoomPostMessage.content
     *
     * @param content the value for dlRoomPostMessage.content
     *
     * @mbggenerated Thu Jul 16 17:57:54 CST 2015
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dlRoomPostMessage.content_type
     *
     * @return the value of dlRoomPostMessage.content_type
     *
     * @mbggenerated Thu Jul 16 17:57:54 CST 2015
     */
    public String getContentType() {
        return contentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dlRoomPostMessage.content_type
     *
     * @param contentType the value for dlRoomPostMessage.content_type
     *
     * @mbggenerated Thu Jul 16 17:57:54 CST 2015
     */
    public void setContentType(String contentType) {
        this.contentType = contentType;
    }

}