package com.hndl.mobileplatform.model;

public class DlroomnoticemessageWithBLOBs extends Dlroomnoticemessage {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dlRoomNoticeMessage.content
	 * @mbggenerated  Thu Jul 09 18:03:16 CST 2015
	 */
	private String content;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dlRoomNoticeMessage.content_type
	 * @mbggenerated  Thu Jul 09 18:03:16 CST 2015
	 */
	private String contentType;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dlRoomNoticeMessage.content
	 * @return  the value of dlRoomNoticeMessage.content
	 * @mbggenerated  Thu Jul 09 18:03:16 CST 2015
	 */
	public String getContent() {
		return content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dlRoomNoticeMessage.content
	 * @param content  the value for dlRoomNoticeMessage.content
	 * @mbggenerated  Thu Jul 09 18:03:16 CST 2015
	 */
	public void setContent(String content) {
		this.content = content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dlRoomNoticeMessage.content_type
	 * @return  the value of dlRoomNoticeMessage.content_type
	 * @mbggenerated  Thu Jul 09 18:03:16 CST 2015
	 */
	public String getContentType() {
		return contentType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dlRoomNoticeMessage.content_type
	 * @param contentType  the value for dlRoomNoticeMessage.content_type
	 * @mbggenerated  Thu Jul 09 18:03:16 CST 2015
	 */
	public void setContentType(String contentType) {
		this.contentType = contentType;
	}
}