package com.hndl.mobileplatform.model;

public class Dlroomnoticemessage {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dlRoomNoticeMessage.id
     *
     * @mbggenerated Thu Jul 09 18:03:16 CST 2015
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dlRoomNoticeMessage.noticeid
     *
     * @mbggenerated Thu Jul 09 18:03:16 CST 2015
     */
    private String noticeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dlRoomNoticeMessage.createid
     *
     * @mbggenerated Thu Jul 09 18:03:16 CST 2015
     */
    private String createid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dlRoomNoticeMessage.createtime
     *
     * @mbggenerated Thu Jul 09 18:03:16 CST 2015
     */
    private String createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dlRoomNoticeMessage.bz1
     *
     * @mbggenerated Thu Jul 09 18:03:16 CST 2015
     */
    private String bz1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dlRoomNoticeMessage.bz2
     *
     * @mbggenerated Thu Jul 09 18:03:16 CST 2015
     */
    private String bz2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dlRoomNoticeMessage.bz3
     *
     * @mbggenerated Thu Jul 09 18:03:16 CST 2015
     */
    private String bz3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dlRoomNoticeMessage.bz4
     *
     * @mbggenerated Thu Jul 09 18:03:16 CST 2015
     */
    private String bz4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dlRoomNoticeMessage.bz5
     *
     * @mbggenerated Thu Jul 09 18:03:16 CST 2015
     */
    private String bz5;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dlRoomNoticeMessage.id
     *
     * @return the value of dlRoomNoticeMessage.id
     *
     * @mbggenerated Thu Jul 09 18:03:16 CST 2015
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dlRoomNoticeMessage.id
     *
     * @param id the value for dlRoomNoticeMessage.id
     *
     * @mbggenerated Thu Jul 09 18:03:16 CST 2015
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dlRoomNoticeMessage.noticeid
     *
     * @return the value of dlRoomNoticeMessage.noticeid
     *
     * @mbggenerated Thu Jul 09 18:03:16 CST 2015
     */
    public String getNoticeid() {
        return noticeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dlRoomNoticeMessage.noticeid
     *
     * @param noticeid the value for dlRoomNoticeMessage.noticeid
     *
     * @mbggenerated Thu Jul 09 18:03:16 CST 2015
     */
    public void setNoticeid(String noticeid) {
        this.noticeid = noticeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dlRoomNoticeMessage.createid
     *
     * @return the value of dlRoomNoticeMessage.createid
     *
     * @mbggenerated Thu Jul 09 18:03:16 CST 2015
     */
    public String getCreateid() {
        return createid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dlRoomNoticeMessage.createid
     *
     * @param createid the value for dlRoomNoticeMessage.createid
     *
     * @mbggenerated Thu Jul 09 18:03:16 CST 2015
     */
    public void setCreateid(String createid) {
        this.createid = createid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dlRoomNoticeMessage.createtime
     *
     * @return the value of dlRoomNoticeMessage.createtime
     *
     * @mbggenerated Thu Jul 09 18:03:16 CST 2015
     */
    public String getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dlRoomNoticeMessage.createtime
     *
     * @param createtime the value for dlRoomNoticeMessage.createtime
     *
     * @mbggenerated Thu Jul 09 18:03:16 CST 2015
     */
    public void setCreatetime(String createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dlRoomNoticeMessage.bz1
     *
     * @return the value of dlRoomNoticeMessage.bz1
     *
     * @mbggenerated Thu Jul 09 18:03:16 CST 2015
     */
    public String getBz1() {
        return bz1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dlRoomNoticeMessage.bz1
     *
     * @param bz1 the value for dlRoomNoticeMessage.bz1
     *
     * @mbggenerated Thu Jul 09 18:03:16 CST 2015
     */
    public void setBz1(String bz1) {
        this.bz1 = bz1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dlRoomNoticeMessage.bz2
     *
     * @return the value of dlRoomNoticeMessage.bz2
     *
     * @mbggenerated Thu Jul 09 18:03:16 CST 2015
     */
    public String getBz2() {
        return bz2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dlRoomNoticeMessage.bz2
     *
     * @param bz2 the value for dlRoomNoticeMessage.bz2
     *
     * @mbggenerated Thu Jul 09 18:03:16 CST 2015
     */
    public void setBz2(String bz2) {
        this.bz2 = bz2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dlRoomNoticeMessage.bz3
     *
     * @return the value of dlRoomNoticeMessage.bz3
     *
     * @mbggenerated Thu Jul 09 18:03:16 CST 2015
     */
    public String getBz3() {
        return bz3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dlRoomNoticeMessage.bz3
     *
     * @param bz3 the value for dlRoomNoticeMessage.bz3
     *
     * @mbggenerated Thu Jul 09 18:03:16 CST 2015
     */
    public void setBz3(String bz3) {
        this.bz3 = bz3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dlRoomNoticeMessage.bz4
     *
     * @return the value of dlRoomNoticeMessage.bz4
     *
     * @mbggenerated Thu Jul 09 18:03:16 CST 2015
     */
    public String getBz4() {
        return bz4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dlRoomNoticeMessage.bz4
     *
     * @param bz4 the value for dlRoomNoticeMessage.bz4
     *
     * @mbggenerated Thu Jul 09 18:03:16 CST 2015
     */
    public void setBz4(String bz4) {
        this.bz4 = bz4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dlRoomNoticeMessage.bz5
     *
     * @return the value of dlRoomNoticeMessage.bz5
     *
     * @mbggenerated Thu Jul 09 18:03:16 CST 2015
     */
    public String getBz5() {
        return bz5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dlRoomNoticeMessage.bz5
     *
     * @param bz5 the value for dlRoomNoticeMessage.bz5
     *
     * @mbggenerated Thu Jul 09 18:03:16 CST 2015
     */
    public void setBz5(String bz5) {
        this.bz5 = bz5;
    }
}