package com.hndl.mobileplatform.model;

public class DlroomnoticeWithBLOBs extends Dlroomnotice {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dlRoomNotice.content
     *
     * @mbggenerated Thu Jul 09 16:21:19 CST 2015
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dlRoomNotice.content_type
     *
     * @mbggenerated Thu Jul 09 16:21:19 CST 2015
     */
    private String contentType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dlRoomNotice.content
     *
     * @return the value of dlRoomNotice.content
     *
     * @mbggenerated Thu Jul 09 16:21:19 CST 2015
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dlRoomNotice.content
     *
     * @param content the value for dlRoomNotice.content
     *
     * @mbggenerated Thu Jul 09 16:21:19 CST 2015
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dlRoomNotice.content_type
     *
     * @return the value of dlRoomNotice.content_type
     *
     * @mbggenerated Thu Jul 09 16:21:19 CST 2015
     */
    public String getContentType() {
        return contentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dlRoomNotice.content_type
     *
     * @param contentType the value for dlRoomNotice.content_type
     *
     * @mbggenerated Thu Jul 09 16:21:19 CST 2015
     */
    public void setContentType(String contentType) {
        this.contentType = contentType;
    }
}