package com.hndl.mobileplatform.model;

public class Dlroomnotice {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dlRoomNotice.id
     *
     * @mbggenerated Thu Jul 09 16:21:19 CST 2015
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dlRoomNotice.title
     *
     * @mbggenerated Thu Jul 09 16:21:19 CST 2015
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dlRoomNotice.createid
     *
     * @mbggenerated Thu Jul 09 16:21:19 CST 2015
     */
    private String createid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dlRoomNotice.createtime
     *
     * @mbggenerated Thu Jul 09 16:21:19 CST 2015
     */
    private String createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dlRoomNotice.roomid
     *
     * @mbggenerated Thu Jul 09 16:21:19 CST 2015
     */
    private String roomid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dlRoomNotice.bz1
     *
     * @mbggenerated Thu Jul 09 16:21:19 CST 2015
     */
    private String bz1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dlRoomNotice.bz2
     *
     * @mbggenerated Thu Jul 09 16:21:19 CST 2015
     */
    private String bz2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dlRoomNotice.bz3
     *
     * @mbggenerated Thu Jul 09 16:21:19 CST 2015
     */
    private String bz3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dlRoomNotice.bz4
     *
     * @mbggenerated Thu Jul 09 16:21:19 CST 2015
     */
    private String bz4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dlRoomNotice.bz5
     *
     * @mbggenerated Thu Jul 09 16:21:19 CST 2015
     */
    private String bz5;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dlRoomNotice.id
     *
     * @return the value of dlRoomNotice.id
     *
     * @mbggenerated Thu Jul 09 16:21:19 CST 2015
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dlRoomNotice.id
     *
     * @param id the value for dlRoomNotice.id
     *
     * @mbggenerated Thu Jul 09 16:21:19 CST 2015
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dlRoomNotice.title
     *
     * @return the value of dlRoomNotice.title
     *
     * @mbggenerated Thu Jul 09 16:21:19 CST 2015
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dlRoomNotice.title
     *
     * @param title the value for dlRoomNotice.title
     *
     * @mbggenerated Thu Jul 09 16:21:19 CST 2015
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dlRoomNotice.createid
     *
     * @return the value of dlRoomNotice.createid
     *
     * @mbggenerated Thu Jul 09 16:21:19 CST 2015
     */
    public String getCreateid() {
        return createid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dlRoomNotice.createid
     *
     * @param createid the value for dlRoomNotice.createid
     *
     * @mbggenerated Thu Jul 09 16:21:19 CST 2015
     */
    public void setCreateid(String createid) {
        this.createid = createid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dlRoomNotice.createtime
     *
     * @return the value of dlRoomNotice.createtime
     *
     * @mbggenerated Thu Jul 09 16:21:19 CST 2015
     */
    public String getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dlRoomNotice.createtime
     *
     * @param createtime the value for dlRoomNotice.createtime
     *
     * @mbggenerated Thu Jul 09 16:21:19 CST 2015
     */
    public void setCreatetime(String createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dlRoomNotice.roomid
     *
     * @return the value of dlRoomNotice.roomid
     *
     * @mbggenerated Thu Jul 09 16:21:19 CST 2015
     */
    public String getRoomid() {
        return roomid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dlRoomNotice.roomid
     *
     * @param roomid the value for dlRoomNotice.roomid
     *
     * @mbggenerated Thu Jul 09 16:21:19 CST 2015
     */
    public void setRoomid(String roomid) {
        this.roomid = roomid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dlRoomNotice.bz1
     *
     * @return the value of dlRoomNotice.bz1
     *
     * @mbggenerated Thu Jul 09 16:21:19 CST 2015
     */
    public String getBz1() {
        return bz1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dlRoomNotice.bz1
     *
     * @param bz1 the value for dlRoomNotice.bz1
     *
     * @mbggenerated Thu Jul 09 16:21:19 CST 2015
     */
    public void setBz1(String bz1) {
        this.bz1 = bz1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dlRoomNotice.bz2
     *
     * @return the value of dlRoomNotice.bz2
     *
     * @mbggenerated Thu Jul 09 16:21:19 CST 2015
     */
    public String getBz2() {
        return bz2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dlRoomNotice.bz2
     *
     * @param bz2 the value for dlRoomNotice.bz2
     *
     * @mbggenerated Thu Jul 09 16:21:19 CST 2015
     */
    public void setBz2(String bz2) {
        this.bz2 = bz2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dlRoomNotice.bz3
     *
     * @return the value of dlRoomNotice.bz3
     *
     * @mbggenerated Thu Jul 09 16:21:19 CST 2015
     */
    public String getBz3() {
        return bz3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dlRoomNotice.bz3
     *
     * @param bz3 the value for dlRoomNotice.bz3
     *
     * @mbggenerated Thu Jul 09 16:21:19 CST 2015
     */
    public void setBz3(String bz3) {
        this.bz3 = bz3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dlRoomNotice.bz4
     *
     * @return the value of dlRoomNotice.bz4
     *
     * @mbggenerated Thu Jul 09 16:21:19 CST 2015
     */
    public String getBz4() {
        return bz4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dlRoomNotice.bz4
     *
     * @param bz4 the value for dlRoomNotice.bz4
     *
     * @mbggenerated Thu Jul 09 16:21:19 CST 2015
     */
    public void setBz4(String bz4) {
        this.bz4 = bz4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dlRoomNotice.bz5
     *
     * @return the value of dlRoomNotice.bz5
     *
     * @mbggenerated Thu Jul 09 16:21:19 CST 2015
     */
    public String getBz5() {
        return bz5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dlRoomNotice.bz5
     *
     * @param bz5 the value for dlRoomNotice.bz5
     *
     * @mbggenerated Thu Jul 09 16:21:19 CST 2015
     */
    public void setBz5(String bz5) {
        this.bz5 = bz5;
    }
}