package com.hndl.mobileplatform.model;

public class Dlroompostmessage {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dlRoomPostMessage.id
     *
     * @mbggenerated Thu Jul 16 17:57:54 CST 2015
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dlRoomPostMessage.noticeid
     *
     * @mbggenerated Thu Jul 16 17:57:54 CST 2015
     */
    private String noticeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dlRoomPostMessage.createid
     *
     * @mbggenerated Thu Jul 16 17:57:54 CST 2015
     */
    private String createid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dlRoomPostMessage.createtime
     *
     * @mbggenerated Thu Jul 16 17:57:54 CST 2015
     */
    private String createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dlRoomPostMessage.bz1
     *
     * @mbggenerated Thu Jul 16 17:57:54 CST 2015
     */
    private String bz1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dlRoomPostMessage.bz2
     *
     * @mbggenerated Thu Jul 16 17:57:54 CST 2015
     */
    private String bz2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dlRoomPostMessage.bz3
     *
     * @mbggenerated Thu Jul 16 17:57:54 CST 2015
     */
    private String bz3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dlRoomPostMessage.bz4
     *
     * @mbggenerated Thu Jul 16 17:57:54 CST 2015
     */
    private String bz4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dlRoomPostMessage.bz5
     *
     * @mbggenerated Thu Jul 16 17:57:54 CST 2015
     */
    private String bz5;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dlRoomPostMessage.id
     *
     * @return the value of dlRoomPostMessage.id
     *
     * @mbggenerated Thu Jul 16 17:57:54 CST 2015
     */
    //评论人
    private String name;
    //性别
   private String usersex;

	public String getUsersex() {
	return usersex;
}

public void setUsersex(String usersex) {
	this.usersex = usersex;
}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dlRoomPostMessage.id
     *
     * @param id the value for dlRoomPostMessage.id
     *
     * @mbggenerated Thu Jul 16 17:57:54 CST 2015
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dlRoomPostMessage.noticeid
     *
     * @return the value of dlRoomPostMessage.noticeid
     *
     * @mbggenerated Thu Jul 16 17:57:54 CST 2015
     */
    public String getNoticeid() {
        return noticeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dlRoomPostMessage.noticeid
     *
     * @param noticeid the value for dlRoomPostMessage.noticeid
     *
     * @mbggenerated Thu Jul 16 17:57:54 CST 2015
     */
    public void setNoticeid(String noticeid) {
        this.noticeid = noticeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dlRoomPostMessage.createid
     *
     * @return the value of dlRoomPostMessage.createid
     *
     * @mbggenerated Thu Jul 16 17:57:54 CST 2015
     */
    public String getCreateid() {
        return createid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dlRoomPostMessage.createid
     *
     * @param createid the value for dlRoomPostMessage.createid
     *
     * @mbggenerated Thu Jul 16 17:57:54 CST 2015
     */
    public void setCreateid(String createid) {
        this.createid = createid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dlRoomPostMessage.createtime
     *
     * @return the value of dlRoomPostMessage.createtime
     *
     * @mbggenerated Thu Jul 16 17:57:54 CST 2015
     */
    public String getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dlRoomPostMessage.createtime
     *
     * @param createtime the value for dlRoomPostMessage.createtime
     *
     * @mbggenerated Thu Jul 16 17:57:54 CST 2015
     */
    public void setCreatetime(String createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dlRoomPostMessage.bz1
     *
     * @return the value of dlRoomPostMessage.bz1
     *
     * @mbggenerated Thu Jul 16 17:57:54 CST 2015
     */
    public String getBz1() {
        return bz1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dlRoomPostMessage.bz1
     *
     * @param bz1 the value for dlRoomPostMessage.bz1
     *
     * @mbggenerated Thu Jul 16 17:57:54 CST 2015
     */
    public void setBz1(String bz1) {
        this.bz1 = bz1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dlRoomPostMessage.bz2
     *
     * @return the value of dlRoomPostMessage.bz2
     *
     * @mbggenerated Thu Jul 16 17:57:54 CST 2015
     */
    public String getBz2() {
        return bz2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dlRoomPostMessage.bz2
     *
     * @param bz2 the value for dlRoomPostMessage.bz2
     *
     * @mbggenerated Thu Jul 16 17:57:54 CST 2015
     */
    public void setBz2(String bz2) {
        this.bz2 = bz2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dlRoomPostMessage.bz3
     *
     * @return the value of dlRoomPostMessage.bz3
     *
     * @mbggenerated Thu Jul 16 17:57:54 CST 2015
     */
    public String getBz3() {
        return bz3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dlRoomPostMessage.bz3
     *
     * @param bz3 the value for dlRoomPostMessage.bz3
     *
     * @mbggenerated Thu Jul 16 17:57:54 CST 2015
     */
    public void setBz3(String bz3) {
        this.bz3 = bz3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dlRoomPostMessage.bz4
     *
     * @return the value of dlRoomPostMessage.bz4
     *
     * @mbggenerated Thu Jul 16 17:57:54 CST 2015
     */
    public String getBz4() {
        return bz4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dlRoomPostMessage.bz4
     *
     * @param bz4 the value for dlRoomPostMessage.bz4
     *
     * @mbggenerated Thu Jul 16 17:57:54 CST 2015
     */
    public void setBz4(String bz4) {
        this.bz4 = bz4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dlRoomPostMessage.bz5
     *
     * @return the value of dlRoomPostMessage.bz5
     *
     * @mbggenerated Thu Jul 16 17:57:54 CST 2015
     */
    public String getBz5() {
        return bz5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dlRoomPostMessage.bz5
     *
     * @param bz5 the value for dlRoomPostMessage.bz5
     *
     * @mbggenerated Thu Jul 16 17:57:54 CST 2015
     */
    public void setBz5(String bz5) {
        this.bz5 = bz5;
    }
}