package com.hndl.mobileplatform.model;

public class Dlroomaffiche {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dlRoomAffiche.afficheid
     *
     * @mbggenerated Thu Jul 16 17:53:57 CST 2015
     */
    private String afficheid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dlRoomAffiche.roomid
     *
     * @mbggenerated Thu Jul 16 17:53:57 CST 2015
     */
    private String roomid;
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dlRoomAffiche.affichename
     *
     * @mbggenerated Thu Jul 16 17:53:57 CST 2015
     */
    private String affichename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dlRoomAffiche.imagename
     *
     * @mbggenerated Thu Jul 16 17:53:57 CST 2015
     */
    private String imagename;

    
    public String getDepartment() {
		return department;
	}

	public void setDepartment(String department) {
		this.department = department;
	}

	private String department;
    
    
   

	public String getUserName() {
		return userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dlRoomAffiche.imagepath
     *
     * @mbggenerated Thu Jul 16 17:53:57 CST 2015
     */
    private String imagepath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dlRoomAffiche.imagesize
     *
     * @mbggenerated Thu Jul 16 17:53:57 CST 2015
     */
    private String imagesize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dlRoomAffiche.bz1
     *
     * @mbggenerated Thu Jul 16 17:53:57 CST 2015
     */
    private String bz1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dlRoomAffiche.bz2
     *
     * @mbggenerated Thu Jul 16 17:53:57 CST 2015
     */
    private String bz2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dlRoomAffiche.bz3
     *
     * @mbggenerated Thu Jul 16 17:53:57 CST 2015
     */
    private String bz3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dlRoomAffiche.bz4
     *
     * @mbggenerated Thu Jul 16 17:53:57 CST 2015
     */
    private String bz4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dlRoomAffiche.bz5
     *
     * @mbggenerated Thu Jul 16 17:53:57 CST 2015
     */
    private String bz5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dlRoomAffiche.createid
     *
     * @mbggenerated Thu Jul 16 17:53:57 CST 2015
     */
    private String createid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dlRoomAffiche.createtime
     *
     * @mbggenerated Thu Jul 16 17:53:57 CST 2015
     */
    private String createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dlRoomAffiche.content
     *
     * @mbggenerated Thu Jul 16 17:53:57 CST 2015
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dlRoomAffiche.afficheid
     *
     * @return the value of dlRoomAffiche.afficheid
     *
     * @mbggenerated Thu Jul 16 17:53:57 CST 2015
     */
    public String getAfficheid() {
        return afficheid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dlRoomAffiche.afficheid
     *
     * @param afficheid the value for dlRoomAffiche.afficheid
     *
     * @mbggenerated Thu Jul 16 17:53:57 CST 2015
     */
    public void setAfficheid(String afficheid) {
        this.afficheid = afficheid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dlRoomAffiche.roomid
     *
     * @return the value of dlRoomAffiche.roomid
     *
     * @mbggenerated Thu Jul 16 17:53:57 CST 2015
     */
    public String getRoomid() {
        return roomid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dlRoomAffiche.roomid
     *
     * @param roomid the value for dlRoomAffiche.roomid
     *
     * @mbggenerated Thu Jul 16 17:53:57 CST 2015
     */
    public void setRoomid(String roomid) {
        this.roomid = roomid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dlRoomAffiche.affichename
     *
     * @return the value of dlRoomAffiche.affichename
     *
     * @mbggenerated Thu Jul 16 17:53:57 CST 2015
     */
    public String getAffichename() {
        return affichename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dlRoomAffiche.affichename
     *
     * @param affichename the value for dlRoomAffiche.affichename
     *
     * @mbggenerated Thu Jul 16 17:53:57 CST 2015
     */
    public void setAffichename(String affichename) {
        this.affichename = affichename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dlRoomAffiche.imagename
     *
     * @return the value of dlRoomAffiche.imagename
     *
     * @mbggenerated Thu Jul 16 17:53:57 CST 2015
     */
    public String getImagename() {
        return imagename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dlRoomAffiche.imagename
     *
     * @param imagename the value for dlRoomAffiche.imagename
     *
     * @mbggenerated Thu Jul 16 17:53:57 CST 2015
     */
    public void setImagename(String imagename) {
        this.imagename = imagename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dlRoomAffiche.imagepath
     *
     * @return the value of dlRoomAffiche.imagepath
     *
     * @mbggenerated Thu Jul 16 17:53:57 CST 2015
     */
    public String getImagepath() {
        return imagepath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dlRoomAffiche.imagepath
     *
     * @param imagepath the value for dlRoomAffiche.imagepath
     *
     * @mbggenerated Thu Jul 16 17:53:57 CST 2015
     */
    public void setImagepath(String imagepath) {
        this.imagepath = imagepath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dlRoomAffiche.imagesize
     *
     * @return the value of dlRoomAffiche.imagesize
     *
     * @mbggenerated Thu Jul 16 17:53:57 CST 2015
     */
    public String getImagesize() {
        return imagesize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dlRoomAffiche.imagesize
     *
     * @param imagesize the value for dlRoomAffiche.imagesize
     *
     * @mbggenerated Thu Jul 16 17:53:57 CST 2015
     */
    public void setImagesize(String imagesize) {
        this.imagesize = imagesize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dlRoomAffiche.bz1
     *
     * @return the value of dlRoomAffiche.bz1
     *
     * @mbggenerated Thu Jul 16 17:53:57 CST 2015
     */
    public String getBz1() {
        return bz1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dlRoomAffiche.bz1
     *
     * @param bz1 the value for dlRoomAffiche.bz1
     *
     * @mbggenerated Thu Jul 16 17:53:57 CST 2015
     */
    public void setBz1(String bz1) {
        this.bz1 = bz1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dlRoomAffiche.bz2
     *
     * @return the value of dlRoomAffiche.bz2
     *
     * @mbggenerated Thu Jul 16 17:53:57 CST 2015
     */
    public String getBz2() {
        return bz2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dlRoomAffiche.bz2
     *
     * @param bz2 the value for dlRoomAffiche.bz2
     *
     * @mbggenerated Thu Jul 16 17:53:57 CST 2015
     */
    public void setBz2(String bz2) {
        this.bz2 = bz2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dlRoomAffiche.bz3
     *
     * @return the value of dlRoomAffiche.bz3
     *
     * @mbggenerated Thu Jul 16 17:53:57 CST 2015
     */
    public String getBz3() {
        return bz3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dlRoomAffiche.bz3
     *
     * @param bz3 the value for dlRoomAffiche.bz3
     *
     * @mbggenerated Thu Jul 16 17:53:57 CST 2015
     */
    public void setBz3(String bz3) {
        this.bz3 = bz3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dlRoomAffiche.bz4
     *
     * @return the value of dlRoomAffiche.bz4
     *
     * @mbggenerated Thu Jul 16 17:53:57 CST 2015
     */
    public String getBz4() {
        return bz4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dlRoomAffiche.bz4
     *
     * @param bz4 the value for dlRoomAffiche.bz4
     *
     * @mbggenerated Thu Jul 16 17:53:57 CST 2015
     */
    public void setBz4(String bz4) {
        this.bz4 = bz4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dlRoomAffiche.bz5
     *
     * @return the value of dlRoomAffiche.bz5
     *
     * @mbggenerated Thu Jul 16 17:53:57 CST 2015
     */
    public String getBz5() {
        return bz5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dlRoomAffiche.bz5
     *
     * @param bz5 the value for dlRoomAffiche.bz5
     *
     * @mbggenerated Thu Jul 16 17:53:57 CST 2015
     */
    public void setBz5(String bz5) {
        this.bz5 = bz5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dlRoomAffiche.createid
     *
     * @return the value of dlRoomAffiche.createid
     *
     * @mbggenerated Thu Jul 16 17:53:57 CST 2015
     */
    public String getCreateid() {
        return createid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dlRoomAffiche.createid
     *
     * @param createid the value for dlRoomAffiche.createid
     *
     * @mbggenerated Thu Jul 16 17:53:57 CST 2015
     */
    public void setCreateid(String createid) {
        this.createid = createid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dlRoomAffiche.createtime
     *
     * @return the value of dlRoomAffiche.createtime
     *
     * @mbggenerated Thu Jul 16 17:53:57 CST 2015
     */
    public String getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dlRoomAffiche.createtime
     *
     * @param createtime the value for dlRoomAffiche.createtime
     *
     * @mbggenerated Thu Jul 16 17:53:57 CST 2015
     */
    public void setCreatetime(String createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dlRoomAffiche.content
     *
     * @return the value of dlRoomAffiche.content
     *
     * @mbggenerated Thu Jul 16 17:53:57 CST 2015
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dlRoomAffiche.content
     *
     * @param content the value for dlRoomAffiche.content
     *
     * @mbggenerated Thu Jul 16 17:53:57 CST 2015
     */
    public void setContent(String content) {
        this.content = content;
    }
}