package com.hndl.mobileplatform.model;

import java.util.Date;

public class Dlsoftversion {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dlSoftVersion.versionId
     *
     * @mbggenerated Thu Jul 02 08:48:19 CST 2015
     */
    private String versionid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dlSoftVersion.versionCode
     *
     * @mbggenerated Thu Jul 02 08:48:19 CST 2015
     */
    private String versioncode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dlSoftVersion.versionName
     *
     * @mbggenerated Thu Jul 02 08:48:19 CST 2015
     */
    private String versionname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dlSoftVersion.versionDescription
     *
     * @mbggenerated Thu Jul 02 08:48:19 CST 2015
     */
    private String versiondescription;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dlSoftVersion.downloadurl
     *
     * @mbggenerated Thu Jul 02 08:48:19 CST 2015
     */
    private String downloadurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dlSoftVersion.createtime
     *
     * @mbggenerated Thu Jul 02 08:48:19 CST 2015
     */
    private Date createtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dlSoftVersion.versionId
     *
     * @return the value of dlSoftVersion.versionId
     *
     * @mbggenerated Thu Jul 02 08:48:19 CST 2015
     */
    public String getVersionid() {
        return versionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dlSoftVersion.versionId
     *
     * @param versionid the value for dlSoftVersion.versionId
     *
     * @mbggenerated Thu Jul 02 08:48:19 CST 2015
     */
    public void setVersionid(String versionid) {
        this.versionid = versionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dlSoftVersion.versionCode
     *
     * @return the value of dlSoftVersion.versionCode
     *
     * @mbggenerated Thu Jul 02 08:48:19 CST 2015
     */
    public String getVersioncode() {
        return versioncode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dlSoftVersion.versionCode
     *
     * @param versioncode the value for dlSoftVersion.versionCode
     *
     * @mbggenerated Thu Jul 02 08:48:19 CST 2015
     */
    public void setVersioncode(String versioncode) {
        this.versioncode = versioncode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dlSoftVersion.versionName
     *
     * @return the value of dlSoftVersion.versionName
     *
     * @mbggenerated Thu Jul 02 08:48:19 CST 2015
     */
    public String getVersionname() {
        return versionname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dlSoftVersion.versionName
     *
     * @param versionname the value for dlSoftVersion.versionName
     *
     * @mbggenerated Thu Jul 02 08:48:19 CST 2015
     */
    public void setVersionname(String versionname) {
        this.versionname = versionname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dlSoftVersion.versionDescription
     *
     * @return the value of dlSoftVersion.versionDescription
     *
     * @mbggenerated Thu Jul 02 08:48:19 CST 2015
     */
    public String getVersiondescription() {
        return versiondescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dlSoftVersion.versionDescription
     *
     * @param versiondescription the value for dlSoftVersion.versionDescription
     *
     * @mbggenerated Thu Jul 02 08:48:19 CST 2015
     */
    public void setVersiondescription(String versiondescription) {
        this.versiondescription = versiondescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dlSoftVersion.downloadurl
     *
     * @return the value of dlSoftVersion.downloadurl
     *
     * @mbggenerated Thu Jul 02 08:48:19 CST 2015
     */
    public String getDownloadurl() {
        return downloadurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dlSoftVersion.downloadurl
     *
     * @param downloadurl the value for dlSoftVersion.downloadurl
     *
     * @mbggenerated Thu Jul 02 08:48:19 CST 2015
     */
    public void setDownloadurl(String downloadurl) {
        this.downloadurl = downloadurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dlSoftVersion.createtime
     *
     * @return the value of dlSoftVersion.createtime
     *
     * @mbggenerated Thu Jul 02 08:48:19 CST 2015
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dlSoftVersion.createtime
     *
     * @param createtime the value for dlSoftVersion.createtime
     *
     * @mbggenerated Thu Jul 02 08:48:19 CST 2015
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }
}