package com.hndl.mobileplatform.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import com.pmcc.soft.core.common.BaseExample;

public class DlsoftversionExample extends BaseExample{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dlSoftVersion
     *
     * @mbggenerated Thu Jul 02 08:48:19 CST 2015
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dlSoftVersion
     *
     * @mbggenerated Thu Jul 02 08:48:19 CST 2015
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dlSoftVersion
     *
     * @mbggenerated Thu Jul 02 08:48:19 CST 2015
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dlSoftVersion
     *
     * @mbggenerated Thu Jul 02 08:48:19 CST 2015
     */
    public DlsoftversionExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dlSoftVersion
     *
     * @mbggenerated Thu Jul 02 08:48:19 CST 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dlSoftVersion
     *
     * @mbggenerated Thu Jul 02 08:48:19 CST 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dlSoftVersion
     *
     * @mbggenerated Thu Jul 02 08:48:19 CST 2015
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dlSoftVersion
     *
     * @mbggenerated Thu Jul 02 08:48:19 CST 2015
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dlSoftVersion
     *
     * @mbggenerated Thu Jul 02 08:48:19 CST 2015
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dlSoftVersion
     *
     * @mbggenerated Thu Jul 02 08:48:19 CST 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dlSoftVersion
     *
     * @mbggenerated Thu Jul 02 08:48:19 CST 2015
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dlSoftVersion
     *
     * @mbggenerated Thu Jul 02 08:48:19 CST 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dlSoftVersion
     *
     * @mbggenerated Thu Jul 02 08:48:19 CST 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dlSoftVersion
     *
     * @mbggenerated Thu Jul 02 08:48:19 CST 2015
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dlSoftVersion
     *
     * @mbggenerated Thu Jul 02 08:48:19 CST 2015
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andVersionidIsNull() {
            addCriterion("versionId is null");
            return (Criteria) this;
        }

        public Criteria andVersionidIsNotNull() {
            addCriterion("versionId is not null");
            return (Criteria) this;
        }

        public Criteria andVersionidEqualTo(String value) {
            addCriterion("versionId =", value, "versionid");
            return (Criteria) this;
        }

        public Criteria andVersionidNotEqualTo(String value) {
            addCriterion("versionId <>", value, "versionid");
            return (Criteria) this;
        }

        public Criteria andVersionidGreaterThan(String value) {
            addCriterion("versionId >", value, "versionid");
            return (Criteria) this;
        }

        public Criteria andVersionidGreaterThanOrEqualTo(String value) {
            addCriterion("versionId >=", value, "versionid");
            return (Criteria) this;
        }

        public Criteria andVersionidLessThan(String value) {
            addCriterion("versionId <", value, "versionid");
            return (Criteria) this;
        }

        public Criteria andVersionidLessThanOrEqualTo(String value) {
            addCriterion("versionId <=", value, "versionid");
            return (Criteria) this;
        }

        public Criteria andVersionidLike(String value) {
            addCriterion("versionId like", value, "versionid");
            return (Criteria) this;
        }

        public Criteria andVersionidNotLike(String value) {
            addCriterion("versionId not like", value, "versionid");
            return (Criteria) this;
        }

        public Criteria andVersionidIn(List<String> values) {
            addCriterion("versionId in", values, "versionid");
            return (Criteria) this;
        }

        public Criteria andVersionidNotIn(List<String> values) {
            addCriterion("versionId not in", values, "versionid");
            return (Criteria) this;
        }

        public Criteria andVersionidBetween(String value1, String value2) {
            addCriterion("versionId between", value1, value2, "versionid");
            return (Criteria) this;
        }

        public Criteria andVersionidNotBetween(String value1, String value2) {
            addCriterion("versionId not between", value1, value2, "versionid");
            return (Criteria) this;
        }

        public Criteria andVersioncodeIsNull() {
            addCriterion("versionCode is null");
            return (Criteria) this;
        }

        public Criteria andVersioncodeIsNotNull() {
            addCriterion("versionCode is not null");
            return (Criteria) this;
        }

        public Criteria andVersioncodeEqualTo(String value) {
            addCriterion("versionCode =", value, "versioncode");
            return (Criteria) this;
        }

        public Criteria andVersioncodeNotEqualTo(String value) {
            addCriterion("versionCode <>", value, "versioncode");
            return (Criteria) this;
        }

        public Criteria andVersioncodeGreaterThan(String value) {
            addCriterion("versionCode >", value, "versioncode");
            return (Criteria) this;
        }

        public Criteria andVersioncodeGreaterThanOrEqualTo(String value) {
            addCriterion("versionCode >=", value, "versioncode");
            return (Criteria) this;
        }

        public Criteria andVersioncodeLessThan(String value) {
            addCriterion("versionCode <", value, "versioncode");
            return (Criteria) this;
        }

        public Criteria andVersioncodeLessThanOrEqualTo(String value) {
            addCriterion("versionCode <=", value, "versioncode");
            return (Criteria) this;
        }

        public Criteria andVersioncodeLike(String value) {
            addCriterion("versionCode like", value, "versioncode");
            return (Criteria) this;
        }

        public Criteria andVersioncodeNotLike(String value) {
            addCriterion("versionCode not like", value, "versioncode");
            return (Criteria) this;
        }

        public Criteria andVersioncodeIn(List<String> values) {
            addCriterion("versionCode in", values, "versioncode");
            return (Criteria) this;
        }

        public Criteria andVersioncodeNotIn(List<String> values) {
            addCriterion("versionCode not in", values, "versioncode");
            return (Criteria) this;
        }

        public Criteria andVersioncodeBetween(String value1, String value2) {
            addCriterion("versionCode between", value1, value2, "versioncode");
            return (Criteria) this;
        }

        public Criteria andVersioncodeNotBetween(String value1, String value2) {
            addCriterion("versionCode not between", value1, value2, "versioncode");
            return (Criteria) this;
        }

        public Criteria andVersionnameIsNull() {
            addCriterion("versionName is null");
            return (Criteria) this;
        }

        public Criteria andVersionnameIsNotNull() {
            addCriterion("versionName is not null");
            return (Criteria) this;
        }

        public Criteria andVersionnameEqualTo(String value) {
            addCriterion("versionName =", value, "versionname");
            return (Criteria) this;
        }

        public Criteria andVersionnameNotEqualTo(String value) {
            addCriterion("versionName <>", value, "versionname");
            return (Criteria) this;
        }

        public Criteria andVersionnameGreaterThan(String value) {
            addCriterion("versionName >", value, "versionname");
            return (Criteria) this;
        }

        public Criteria andVersionnameGreaterThanOrEqualTo(String value) {
            addCriterion("versionName >=", value, "versionname");
            return (Criteria) this;
        }

        public Criteria andVersionnameLessThan(String value) {
            addCriterion("versionName <", value, "versionname");
            return (Criteria) this;
        }

        public Criteria andVersionnameLessThanOrEqualTo(String value) {
            addCriterion("versionName <=", value, "versionname");
            return (Criteria) this;
        }

        public Criteria andVersionnameLike(String value) {
            addCriterion("versionName like", value, "versionname");
            return (Criteria) this;
        }

        public Criteria andVersionnameNotLike(String value) {
            addCriterion("versionName not like", value, "versionname");
            return (Criteria) this;
        }

        public Criteria andVersionnameIn(List<String> values) {
            addCriterion("versionName in", values, "versionname");
            return (Criteria) this;
        }

        public Criteria andVersionnameNotIn(List<String> values) {
            addCriterion("versionName not in", values, "versionname");
            return (Criteria) this;
        }

        public Criteria andVersionnameBetween(String value1, String value2) {
            addCriterion("versionName between", value1, value2, "versionname");
            return (Criteria) this;
        }

        public Criteria andVersionnameNotBetween(String value1, String value2) {
            addCriterion("versionName not between", value1, value2, "versionname");
            return (Criteria) this;
        }

        public Criteria andVersiondescriptionIsNull() {
            addCriterion("versionDescription is null");
            return (Criteria) this;
        }

        public Criteria andVersiondescriptionIsNotNull() {
            addCriterion("versionDescription is not null");
            return (Criteria) this;
        }

        public Criteria andVersiondescriptionEqualTo(String value) {
            addCriterion("versionDescription =", value, "versiondescription");
            return (Criteria) this;
        }

        public Criteria andVersiondescriptionNotEqualTo(String value) {
            addCriterion("versionDescription <>", value, "versiondescription");
            return (Criteria) this;
        }

        public Criteria andVersiondescriptionGreaterThan(String value) {
            addCriterion("versionDescription >", value, "versiondescription");
            return (Criteria) this;
        }

        public Criteria andVersiondescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("versionDescription >=", value, "versiondescription");
            return (Criteria) this;
        }

        public Criteria andVersiondescriptionLessThan(String value) {
            addCriterion("versionDescription <", value, "versiondescription");
            return (Criteria) this;
        }

        public Criteria andVersiondescriptionLessThanOrEqualTo(String value) {
            addCriterion("versionDescription <=", value, "versiondescription");
            return (Criteria) this;
        }

        public Criteria andVersiondescriptionLike(String value) {
            addCriterion("versionDescription like", value, "versiondescription");
            return (Criteria) this;
        }

        public Criteria andVersiondescriptionNotLike(String value) {
            addCriterion("versionDescription not like", value, "versiondescription");
            return (Criteria) this;
        }

        public Criteria andVersiondescriptionIn(List<String> values) {
            addCriterion("versionDescription in", values, "versiondescription");
            return (Criteria) this;
        }

        public Criteria andVersiondescriptionNotIn(List<String> values) {
            addCriterion("versionDescription not in", values, "versiondescription");
            return (Criteria) this;
        }

        public Criteria andVersiondescriptionBetween(String value1, String value2) {
            addCriterion("versionDescription between", value1, value2, "versiondescription");
            return (Criteria) this;
        }

        public Criteria andVersiondescriptionNotBetween(String value1, String value2) {
            addCriterion("versionDescription not between", value1, value2, "versiondescription");
            return (Criteria) this;
        }

        public Criteria andDownloadurlIsNull() {
            addCriterion("downloadurl is null");
            return (Criteria) this;
        }

        public Criteria andDownloadurlIsNotNull() {
            addCriterion("downloadurl is not null");
            return (Criteria) this;
        }

        public Criteria andDownloadurlEqualTo(String value) {
            addCriterion("downloadurl =", value, "downloadurl");
            return (Criteria) this;
        }

        public Criteria andDownloadurlNotEqualTo(String value) {
            addCriterion("downloadurl <>", value, "downloadurl");
            return (Criteria) this;
        }

        public Criteria andDownloadurlGreaterThan(String value) {
            addCriterion("downloadurl >", value, "downloadurl");
            return (Criteria) this;
        }

        public Criteria andDownloadurlGreaterThanOrEqualTo(String value) {
            addCriterion("downloadurl >=", value, "downloadurl");
            return (Criteria) this;
        }

        public Criteria andDownloadurlLessThan(String value) {
            addCriterion("downloadurl <", value, "downloadurl");
            return (Criteria) this;
        }

        public Criteria andDownloadurlLessThanOrEqualTo(String value) {
            addCriterion("downloadurl <=", value, "downloadurl");
            return (Criteria) this;
        }

        public Criteria andDownloadurlLike(String value) {
            addCriterion("downloadurl like", value, "downloadurl");
            return (Criteria) this;
        }

        public Criteria andDownloadurlNotLike(String value) {
            addCriterion("downloadurl not like", value, "downloadurl");
            return (Criteria) this;
        }

        public Criteria andDownloadurlIn(List<String> values) {
            addCriterion("downloadurl in", values, "downloadurl");
            return (Criteria) this;
        }

        public Criteria andDownloadurlNotIn(List<String> values) {
            addCriterion("downloadurl not in", values, "downloadurl");
            return (Criteria) this;
        }

        public Criteria andDownloadurlBetween(String value1, String value2) {
            addCriterion("downloadurl between", value1, value2, "downloadurl");
            return (Criteria) this;
        }

        public Criteria andDownloadurlNotBetween(String value1, String value2) {
            addCriterion("downloadurl not between", value1, value2, "downloadurl");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIsNull() {
            addCriterion("createtime is null");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIsNotNull() {
            addCriterion("createtime is not null");
            return (Criteria) this;
        }

        public Criteria andCreatetimeEqualTo(Date value) {
            addCriterion("createtime =", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotEqualTo(Date value) {
            addCriterion("createtime <>", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeGreaterThan(Date value) {
            addCriterion("createtime >", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("createtime >=", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLessThan(Date value) {
            addCriterion("createtime <", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLessThanOrEqualTo(Date value) {
            addCriterion("createtime <=", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIn(List<Date> values) {
            addCriterion("createtime in", values, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotIn(List<Date> values) {
            addCriterion("createtime not in", values, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeBetween(Date value1, Date value2) {
            addCriterion("createtime between", value1, value2, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotBetween(Date value1, Date value2) {
            addCriterion("createtime not between", value1, value2, "createtime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dlSoftVersion
     *
     * @mbggenerated do_not_delete_during_merge Thu Jul 02 08:48:19 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dlSoftVersion
     *
     * @mbggenerated Thu Jul 02 08:48:19 CST 2015
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}