package com.hndl.mobileplatform.model;

public class Dlspacemanager {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dlSpaceManager.spaceid
     *
     * @mbggenerated Mon Jul 27 11:25:13 CST 2015
     */
    private String spaceid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dlSpaceManager.pacename
     *
     * @mbggenerated Mon Jul 27 11:25:13 CST 2015
     */
    private String pacename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dlSpaceManager.roomoruserid
     *
     * @mbggenerated Mon Jul 27 11:25:13 CST 2015
     */
    private String roomoruserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dlSpaceManager.spacesize
     *
     * @mbggenerated Mon Jul 27 11:25:13 CST 2015
     */
    private String spacesize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dlSpaceManager.spaceusesize
     *
     * @mbggenerated Mon Jul 27 11:25:13 CST 2015
     */
    private String spaceusesize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dlSpaceManager.createtime
     *
     * @mbggenerated Mon Jul 27 11:25:13 CST 2015
     */
    private String createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dlSpaceManager.createid
     *
     * @mbggenerated Mon Jul 27 11:25:13 CST 2015
     */
    private String createid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dlSpaceManager.type
     *
     * @mbggenerated Mon Jul 27 11:25:13 CST 2015
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dlSpaceManager.bz1
     *
     * @mbggenerated Mon Jul 27 11:25:13 CST 2015
     */
    private String bz1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dlSpaceManager.bz2
     *
     * @mbggenerated Mon Jul 27 11:25:13 CST 2015
     */
    private String bz2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dlSpaceManager.bz3
     *
     * @mbggenerated Mon Jul 27 11:25:13 CST 2015
     */
    private String bz3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dlSpaceManager.bz4
     *
     * @mbggenerated Mon Jul 27 11:25:13 CST 2015
     */
    private String bz4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dlSpaceManager.bz5
     *
     * @mbggenerated Mon Jul 27 11:25:13 CST 2015
     */
    private String bz5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dlSpaceManager.roomoruser
     *
     * @mbggenerated Mon Jul 27 11:25:13 CST 2015
     */
    private Integer roomoruser;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dlSpaceManager.spaceid
     *
     * @return the value of dlSpaceManager.spaceid
     *
     * @mbggenerated Mon Jul 27 11:25:13 CST 2015
     */
    public String getSpaceid() {
        return spaceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dlSpaceManager.spaceid
     *
     * @param spaceid the value for dlSpaceManager.spaceid
     *
     * @mbggenerated Mon Jul 27 11:25:13 CST 2015
     */
    public void setSpaceid(String spaceid) {
        this.spaceid = spaceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dlSpaceManager.pacename
     *
     * @return the value of dlSpaceManager.pacename
     *
     * @mbggenerated Mon Jul 27 11:25:13 CST 2015
     */
    public String getPacename() {
        return pacename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dlSpaceManager.pacename
     *
     * @param pacename the value for dlSpaceManager.pacename
     *
     * @mbggenerated Mon Jul 27 11:25:13 CST 2015
     */
    public void setPacename(String pacename) {
        this.pacename = pacename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dlSpaceManager.roomoruserid
     *
     * @return the value of dlSpaceManager.roomoruserid
     *
     * @mbggenerated Mon Jul 27 11:25:13 CST 2015
     */
    public String getRoomoruserid() {
        return roomoruserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dlSpaceManager.roomoruserid
     *
     * @param roomoruserid the value for dlSpaceManager.roomoruserid
     *
     * @mbggenerated Mon Jul 27 11:25:13 CST 2015
     */
    public void setRoomoruserid(String roomoruserid) {
        this.roomoruserid = roomoruserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dlSpaceManager.spacesize
     *
     * @return the value of dlSpaceManager.spacesize
     *
     * @mbggenerated Mon Jul 27 11:25:13 CST 2015
     */
    public String getSpacesize() {
        return spacesize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dlSpaceManager.spacesize
     *
     * @param spacesize the value for dlSpaceManager.spacesize
     *
     * @mbggenerated Mon Jul 27 11:25:13 CST 2015
     */
    public void setSpacesize(String spacesize) {
        this.spacesize = spacesize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dlSpaceManager.spaceusesize
     *
     * @return the value of dlSpaceManager.spaceusesize
     *
     * @mbggenerated Mon Jul 27 11:25:13 CST 2015
     */
    public String getSpaceusesize() {
        return spaceusesize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dlSpaceManager.spaceusesize
     *
     * @param spaceusesize the value for dlSpaceManager.spaceusesize
     *
     * @mbggenerated Mon Jul 27 11:25:13 CST 2015
     */
    public void setSpaceusesize(String spaceusesize) {
        this.spaceusesize = spaceusesize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dlSpaceManager.createtime
     *
     * @return the value of dlSpaceManager.createtime
     *
     * @mbggenerated Mon Jul 27 11:25:13 CST 2015
     */
    public String getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dlSpaceManager.createtime
     *
     * @param createtime the value for dlSpaceManager.createtime
     *
     * @mbggenerated Mon Jul 27 11:25:13 CST 2015
     */
    public void setCreatetime(String createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dlSpaceManager.createid
     *
     * @return the value of dlSpaceManager.createid
     *
     * @mbggenerated Mon Jul 27 11:25:13 CST 2015
     */
    public String getCreateid() {
        return createid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dlSpaceManager.createid
     *
     * @param createid the value for dlSpaceManager.createid
     *
     * @mbggenerated Mon Jul 27 11:25:13 CST 2015
     */
    public void setCreateid(String createid) {
        this.createid = createid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dlSpaceManager.type
     *
     * @return the value of dlSpaceManager.type
     *
     * @mbggenerated Mon Jul 27 11:25:13 CST 2015
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dlSpaceManager.type
     *
     * @param type the value for dlSpaceManager.type
     *
     * @mbggenerated Mon Jul 27 11:25:13 CST 2015
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dlSpaceManager.bz1
     *
     * @return the value of dlSpaceManager.bz1
     *
     * @mbggenerated Mon Jul 27 11:25:13 CST 2015
     */
    public String getBz1() {
        return bz1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dlSpaceManager.bz1
     *
     * @param bz1 the value for dlSpaceManager.bz1
     *
     * @mbggenerated Mon Jul 27 11:25:13 CST 2015
     */
    public void setBz1(String bz1) {
        this.bz1 = bz1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dlSpaceManager.bz2
     *
     * @return the value of dlSpaceManager.bz2
     *
     * @mbggenerated Mon Jul 27 11:25:13 CST 2015
     */
    public String getBz2() {
        return bz2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dlSpaceManager.bz2
     *
     * @param bz2 the value for dlSpaceManager.bz2
     *
     * @mbggenerated Mon Jul 27 11:25:13 CST 2015
     */
    public void setBz2(String bz2) {
        this.bz2 = bz2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dlSpaceManager.bz3
     *
     * @return the value of dlSpaceManager.bz3
     *
     * @mbggenerated Mon Jul 27 11:25:13 CST 2015
     */
    public String getBz3() {
        return bz3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dlSpaceManager.bz3
     *
     * @param bz3 the value for dlSpaceManager.bz3
     *
     * @mbggenerated Mon Jul 27 11:25:13 CST 2015
     */
    public void setBz3(String bz3) {
        this.bz3 = bz3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dlSpaceManager.bz4
     *
     * @return the value of dlSpaceManager.bz4
     *
     * @mbggenerated Mon Jul 27 11:25:13 CST 2015
     */
    public String getBz4() {
        return bz4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dlSpaceManager.bz4
     *
     * @param bz4 the value for dlSpaceManager.bz4
     *
     * @mbggenerated Mon Jul 27 11:25:13 CST 2015
     */
    public void setBz4(String bz4) {
        this.bz4 = bz4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dlSpaceManager.bz5
     *
     * @return the value of dlSpaceManager.bz5
     *
     * @mbggenerated Mon Jul 27 11:25:13 CST 2015
     */
    public String getBz5() {
        return bz5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dlSpaceManager.bz5
     *
     * @param bz5 the value for dlSpaceManager.bz5
     *
     * @mbggenerated Mon Jul 27 11:25:13 CST 2015
     */
    public void setBz5(String bz5) {
        this.bz5 = bz5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dlSpaceManager.roomoruser
     *
     * @return the value of dlSpaceManager.roomoruser
     *
     * @mbggenerated Mon Jul 27 11:25:13 CST 2015
     */
    public Integer getRoomoruser() {
        return roomoruser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dlSpaceManager.roomoruser
     *
     * @param roomoruser the value for dlSpaceManager.roomoruser
     *
     * @mbggenerated Mon Jul 27 11:25:13 CST 2015
     */
    public void setRoomoruser(Integer roomoruser) {
        this.roomoruser = roomoruser;
    }
}