package com.hndl.mobileplatform.model;

import java.util.ArrayList;
import java.util.List;

public class DlspacemanagerExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dlSpaceManager
     *
     * @mbggenerated Mon Jul 27 11:25:13 CST 2015
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dlSpaceManager
     *
     * @mbggenerated Mon Jul 27 11:25:13 CST 2015
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dlSpaceManager
     *
     * @mbggenerated Mon Jul 27 11:25:13 CST 2015
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dlSpaceManager
     *
     * @mbggenerated Mon Jul 27 11:25:13 CST 2015
     */
    public DlspacemanagerExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dlSpaceManager
     *
     * @mbggenerated Mon Jul 27 11:25:13 CST 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dlSpaceManager
     *
     * @mbggenerated Mon Jul 27 11:25:13 CST 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dlSpaceManager
     *
     * @mbggenerated Mon Jul 27 11:25:13 CST 2015
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dlSpaceManager
     *
     * @mbggenerated Mon Jul 27 11:25:13 CST 2015
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dlSpaceManager
     *
     * @mbggenerated Mon Jul 27 11:25:13 CST 2015
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dlSpaceManager
     *
     * @mbggenerated Mon Jul 27 11:25:13 CST 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dlSpaceManager
     *
     * @mbggenerated Mon Jul 27 11:25:13 CST 2015
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dlSpaceManager
     *
     * @mbggenerated Mon Jul 27 11:25:13 CST 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dlSpaceManager
     *
     * @mbggenerated Mon Jul 27 11:25:13 CST 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dlSpaceManager
     *
     * @mbggenerated Mon Jul 27 11:25:13 CST 2015
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dlSpaceManager
     *
     * @mbggenerated Mon Jul 27 11:25:13 CST 2015
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andSpaceidIsNull() {
            addCriterion("spaceid is null");
            return (Criteria) this;
        }

        public Criteria andSpaceidIsNotNull() {
            addCriterion("spaceid is not null");
            return (Criteria) this;
        }

        public Criteria andSpaceidEqualTo(String value) {
            addCriterion("spaceid =", value, "spaceid");
            return (Criteria) this;
        }

        public Criteria andSpaceidNotEqualTo(String value) {
            addCriterion("spaceid <>", value, "spaceid");
            return (Criteria) this;
        }

        public Criteria andSpaceidGreaterThan(String value) {
            addCriterion("spaceid >", value, "spaceid");
            return (Criteria) this;
        }

        public Criteria andSpaceidGreaterThanOrEqualTo(String value) {
            addCriterion("spaceid >=", value, "spaceid");
            return (Criteria) this;
        }

        public Criteria andSpaceidLessThan(String value) {
            addCriterion("spaceid <", value, "spaceid");
            return (Criteria) this;
        }

        public Criteria andSpaceidLessThanOrEqualTo(String value) {
            addCriterion("spaceid <=", value, "spaceid");
            return (Criteria) this;
        }

        public Criteria andSpaceidLike(String value) {
            addCriterion("spaceid like", value, "spaceid");
            return (Criteria) this;
        }

        public Criteria andSpaceidNotLike(String value) {
            addCriterion("spaceid not like", value, "spaceid");
            return (Criteria) this;
        }

        public Criteria andSpaceidIn(List<String> values) {
            addCriterion("spaceid in", values, "spaceid");
            return (Criteria) this;
        }

        public Criteria andSpaceidNotIn(List<String> values) {
            addCriterion("spaceid not in", values, "spaceid");
            return (Criteria) this;
        }

        public Criteria andSpaceidBetween(String value1, String value2) {
            addCriterion("spaceid between", value1, value2, "spaceid");
            return (Criteria) this;
        }

        public Criteria andSpaceidNotBetween(String value1, String value2) {
            addCriterion("spaceid not between", value1, value2, "spaceid");
            return (Criteria) this;
        }

        public Criteria andPacenameIsNull() {
            addCriterion("pacename is null");
            return (Criteria) this;
        }

        public Criteria andPacenameIsNotNull() {
            addCriterion("pacename is not null");
            return (Criteria) this;
        }

        public Criteria andPacenameEqualTo(String value) {
            addCriterion("pacename =", value, "pacename");
            return (Criteria) this;
        }

        public Criteria andPacenameNotEqualTo(String value) {
            addCriterion("pacename <>", value, "pacename");
            return (Criteria) this;
        }

        public Criteria andPacenameGreaterThan(String value) {
            addCriterion("pacename >", value, "pacename");
            return (Criteria) this;
        }

        public Criteria andPacenameGreaterThanOrEqualTo(String value) {
            addCriterion("pacename >=", value, "pacename");
            return (Criteria) this;
        }

        public Criteria andPacenameLessThan(String value) {
            addCriterion("pacename <", value, "pacename");
            return (Criteria) this;
        }

        public Criteria andPacenameLessThanOrEqualTo(String value) {
            addCriterion("pacename <=", value, "pacename");
            return (Criteria) this;
        }

        public Criteria andPacenameLike(String value) {
            addCriterion("pacename like", value, "pacename");
            return (Criteria) this;
        }

        public Criteria andPacenameNotLike(String value) {
            addCriterion("pacename not like", value, "pacename");
            return (Criteria) this;
        }

        public Criteria andPacenameIn(List<String> values) {
            addCriterion("pacename in", values, "pacename");
            return (Criteria) this;
        }

        public Criteria andPacenameNotIn(List<String> values) {
            addCriterion("pacename not in", values, "pacename");
            return (Criteria) this;
        }

        public Criteria andPacenameBetween(String value1, String value2) {
            addCriterion("pacename between", value1, value2, "pacename");
            return (Criteria) this;
        }

        public Criteria andPacenameNotBetween(String value1, String value2) {
            addCriterion("pacename not between", value1, value2, "pacename");
            return (Criteria) this;
        }

        public Criteria andRoomoruseridIsNull() {
            addCriterion("roomoruserid is null");
            return (Criteria) this;
        }

        public Criteria andRoomoruseridIsNotNull() {
            addCriterion("roomoruserid is not null");
            return (Criteria) this;
        }

        public Criteria andRoomoruseridEqualTo(String value) {
            addCriterion("roomoruserid =", value, "roomoruserid");
            return (Criteria) this;
        }

        public Criteria andRoomoruseridNotEqualTo(String value) {
            addCriterion("roomoruserid <>", value, "roomoruserid");
            return (Criteria) this;
        }

        public Criteria andRoomoruseridGreaterThan(String value) {
            addCriterion("roomoruserid >", value, "roomoruserid");
            return (Criteria) this;
        }

        public Criteria andRoomoruseridGreaterThanOrEqualTo(String value) {
            addCriterion("roomoruserid >=", value, "roomoruserid");
            return (Criteria) this;
        }

        public Criteria andRoomoruseridLessThan(String value) {
            addCriterion("roomoruserid <", value, "roomoruserid");
            return (Criteria) this;
        }

        public Criteria andRoomoruseridLessThanOrEqualTo(String value) {
            addCriterion("roomoruserid <=", value, "roomoruserid");
            return (Criteria) this;
        }

        public Criteria andRoomoruseridLike(String value) {
            addCriterion("roomoruserid like", value, "roomoruserid");
            return (Criteria) this;
        }

        public Criteria andRoomoruseridNotLike(String value) {
            addCriterion("roomoruserid not like", value, "roomoruserid");
            return (Criteria) this;
        }

        public Criteria andRoomoruseridIn(List<String> values) {
            addCriterion("roomoruserid in", values, "roomoruserid");
            return (Criteria) this;
        }

        public Criteria andRoomoruseridNotIn(List<String> values) {
            addCriterion("roomoruserid not in", values, "roomoruserid");
            return (Criteria) this;
        }

        public Criteria andRoomoruseridBetween(String value1, String value2) {
            addCriterion("roomoruserid between", value1, value2, "roomoruserid");
            return (Criteria) this;
        }

        public Criteria andRoomoruseridNotBetween(String value1, String value2) {
            addCriterion("roomoruserid not between", value1, value2, "roomoruserid");
            return (Criteria) this;
        }

        public Criteria andSpacesizeIsNull() {
            addCriterion("spacesize is null");
            return (Criteria) this;
        }

        public Criteria andSpacesizeIsNotNull() {
            addCriterion("spacesize is not null");
            return (Criteria) this;
        }

        public Criteria andSpacesizeEqualTo(String value) {
            addCriterion("spacesize =", value, "spacesize");
            return (Criteria) this;
        }

        public Criteria andSpacesizeNotEqualTo(String value) {
            addCriterion("spacesize <>", value, "spacesize");
            return (Criteria) this;
        }

        public Criteria andSpacesizeGreaterThan(String value) {
            addCriterion("spacesize >", value, "spacesize");
            return (Criteria) this;
        }

        public Criteria andSpacesizeGreaterThanOrEqualTo(String value) {
            addCriterion("spacesize >=", value, "spacesize");
            return (Criteria) this;
        }

        public Criteria andSpacesizeLessThan(String value) {
            addCriterion("spacesize <", value, "spacesize");
            return (Criteria) this;
        }

        public Criteria andSpacesizeLessThanOrEqualTo(String value) {
            addCriterion("spacesize <=", value, "spacesize");
            return (Criteria) this;
        }

        public Criteria andSpacesizeLike(String value) {
            addCriterion("spacesize like", value, "spacesize");
            return (Criteria) this;
        }

        public Criteria andSpacesizeNotLike(String value) {
            addCriterion("spacesize not like", value, "spacesize");
            return (Criteria) this;
        }

        public Criteria andSpacesizeIn(List<String> values) {
            addCriterion("spacesize in", values, "spacesize");
            return (Criteria) this;
        }

        public Criteria andSpacesizeNotIn(List<String> values) {
            addCriterion("spacesize not in", values, "spacesize");
            return (Criteria) this;
        }

        public Criteria andSpacesizeBetween(String value1, String value2) {
            addCriterion("spacesize between", value1, value2, "spacesize");
            return (Criteria) this;
        }

        public Criteria andSpacesizeNotBetween(String value1, String value2) {
            addCriterion("spacesize not between", value1, value2, "spacesize");
            return (Criteria) this;
        }

        public Criteria andSpaceusesizeIsNull() {
            addCriterion("spaceusesize is null");
            return (Criteria) this;
        }

        public Criteria andSpaceusesizeIsNotNull() {
            addCriterion("spaceusesize is not null");
            return (Criteria) this;
        }

        public Criteria andSpaceusesizeEqualTo(String value) {
            addCriterion("spaceusesize =", value, "spaceusesize");
            return (Criteria) this;
        }

        public Criteria andSpaceusesizeNotEqualTo(String value) {
            addCriterion("spaceusesize <>", value, "spaceusesize");
            return (Criteria) this;
        }

        public Criteria andSpaceusesizeGreaterThan(String value) {
            addCriterion("spaceusesize >", value, "spaceusesize");
            return (Criteria) this;
        }

        public Criteria andSpaceusesizeGreaterThanOrEqualTo(String value) {
            addCriterion("spaceusesize >=", value, "spaceusesize");
            return (Criteria) this;
        }

        public Criteria andSpaceusesizeLessThan(String value) {
            addCriterion("spaceusesize <", value, "spaceusesize");
            return (Criteria) this;
        }

        public Criteria andSpaceusesizeLessThanOrEqualTo(String value) {
            addCriterion("spaceusesize <=", value, "spaceusesize");
            return (Criteria) this;
        }

        public Criteria andSpaceusesizeLike(String value) {
            addCriterion("spaceusesize like", value, "spaceusesize");
            return (Criteria) this;
        }

        public Criteria andSpaceusesizeNotLike(String value) {
            addCriterion("spaceusesize not like", value, "spaceusesize");
            return (Criteria) this;
        }

        public Criteria andSpaceusesizeIn(List<String> values) {
            addCriterion("spaceusesize in", values, "spaceusesize");
            return (Criteria) this;
        }

        public Criteria andSpaceusesizeNotIn(List<String> values) {
            addCriterion("spaceusesize not in", values, "spaceusesize");
            return (Criteria) this;
        }

        public Criteria andSpaceusesizeBetween(String value1, String value2) {
            addCriterion("spaceusesize between", value1, value2, "spaceusesize");
            return (Criteria) this;
        }

        public Criteria andSpaceusesizeNotBetween(String value1, String value2) {
            addCriterion("spaceusesize not between", value1, value2, "spaceusesize");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIsNull() {
            addCriterion("createtime is null");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIsNotNull() {
            addCriterion("createtime is not null");
            return (Criteria) this;
        }

        public Criteria andCreatetimeEqualTo(String value) {
            addCriterion("createtime =", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotEqualTo(String value) {
            addCriterion("createtime <>", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeGreaterThan(String value) {
            addCriterion("createtime >", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeGreaterThanOrEqualTo(String value) {
            addCriterion("createtime >=", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLessThan(String value) {
            addCriterion("createtime <", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLessThanOrEqualTo(String value) {
            addCriterion("createtime <=", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLike(String value) {
            addCriterion("createtime like", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotLike(String value) {
            addCriterion("createtime not like", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIn(List<String> values) {
            addCriterion("createtime in", values, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotIn(List<String> values) {
            addCriterion("createtime not in", values, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeBetween(String value1, String value2) {
            addCriterion("createtime between", value1, value2, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotBetween(String value1, String value2) {
            addCriterion("createtime not between", value1, value2, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreateidIsNull() {
            addCriterion("createid is null");
            return (Criteria) this;
        }

        public Criteria andCreateidIsNotNull() {
            addCriterion("createid is not null");
            return (Criteria) this;
        }

        public Criteria andCreateidEqualTo(String value) {
            addCriterion("createid =", value, "createid");
            return (Criteria) this;
        }

        public Criteria andCreateidNotEqualTo(String value) {
            addCriterion("createid <>", value, "createid");
            return (Criteria) this;
        }

        public Criteria andCreateidGreaterThan(String value) {
            addCriterion("createid >", value, "createid");
            return (Criteria) this;
        }

        public Criteria andCreateidGreaterThanOrEqualTo(String value) {
            addCriterion("createid >=", value, "createid");
            return (Criteria) this;
        }

        public Criteria andCreateidLessThan(String value) {
            addCriterion("createid <", value, "createid");
            return (Criteria) this;
        }

        public Criteria andCreateidLessThanOrEqualTo(String value) {
            addCriterion("createid <=", value, "createid");
            return (Criteria) this;
        }

        public Criteria andCreateidLike(String value) {
            addCriterion("createid like", value, "createid");
            return (Criteria) this;
        }

        public Criteria andCreateidNotLike(String value) {
            addCriterion("createid not like", value, "createid");
            return (Criteria) this;
        }

        public Criteria andCreateidIn(List<String> values) {
            addCriterion("createid in", values, "createid");
            return (Criteria) this;
        }

        public Criteria andCreateidNotIn(List<String> values) {
            addCriterion("createid not in", values, "createid");
            return (Criteria) this;
        }

        public Criteria andCreateidBetween(String value1, String value2) {
            addCriterion("createid between", value1, value2, "createid");
            return (Criteria) this;
        }

        public Criteria andCreateidNotBetween(String value1, String value2) {
            addCriterion("createid not between", value1, value2, "createid");
            return (Criteria) this;
        }

        public Criteria andTypeIsNull() {
            addCriterion("type is null");
            return (Criteria) this;
        }

        public Criteria andTypeIsNotNull() {
            addCriterion("type is not null");
            return (Criteria) this;
        }

        public Criteria andTypeEqualTo(Integer value) {
            addCriterion("type =", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotEqualTo(Integer value) {
            addCriterion("type <>", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThan(Integer value) {
            addCriterion("type >", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("type >=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThan(Integer value) {
            addCriterion("type <", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThanOrEqualTo(Integer value) {
            addCriterion("type <=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeIn(List<Integer> values) {
            addCriterion("type in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotIn(List<Integer> values) {
            addCriterion("type not in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeBetween(Integer value1, Integer value2) {
            addCriterion("type between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("type not between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andBz1IsNull() {
            addCriterion("bz1 is null");
            return (Criteria) this;
        }

        public Criteria andBz1IsNotNull() {
            addCriterion("bz1 is not null");
            return (Criteria) this;
        }

        public Criteria andBz1EqualTo(String value) {
            addCriterion("bz1 =", value, "bz1");
            return (Criteria) this;
        }

        public Criteria andBz1NotEqualTo(String value) {
            addCriterion("bz1 <>", value, "bz1");
            return (Criteria) this;
        }

        public Criteria andBz1GreaterThan(String value) {
            addCriterion("bz1 >", value, "bz1");
            return (Criteria) this;
        }

        public Criteria andBz1GreaterThanOrEqualTo(String value) {
            addCriterion("bz1 >=", value, "bz1");
            return (Criteria) this;
        }

        public Criteria andBz1LessThan(String value) {
            addCriterion("bz1 <", value, "bz1");
            return (Criteria) this;
        }

        public Criteria andBz1LessThanOrEqualTo(String value) {
            addCriterion("bz1 <=", value, "bz1");
            return (Criteria) this;
        }

        public Criteria andBz1Like(String value) {
            addCriterion("bz1 like", value, "bz1");
            return (Criteria) this;
        }

        public Criteria andBz1NotLike(String value) {
            addCriterion("bz1 not like", value, "bz1");
            return (Criteria) this;
        }

        public Criteria andBz1In(List<String> values) {
            addCriterion("bz1 in", values, "bz1");
            return (Criteria) this;
        }

        public Criteria andBz1NotIn(List<String> values) {
            addCriterion("bz1 not in", values, "bz1");
            return (Criteria) this;
        }

        public Criteria andBz1Between(String value1, String value2) {
            addCriterion("bz1 between", value1, value2, "bz1");
            return (Criteria) this;
        }

        public Criteria andBz1NotBetween(String value1, String value2) {
            addCriterion("bz1 not between", value1, value2, "bz1");
            return (Criteria) this;
        }

        public Criteria andBz2IsNull() {
            addCriterion("bz2 is null");
            return (Criteria) this;
        }

        public Criteria andBz2IsNotNull() {
            addCriterion("bz2 is not null");
            return (Criteria) this;
        }

        public Criteria andBz2EqualTo(String value) {
            addCriterion("bz2 =", value, "bz2");
            return (Criteria) this;
        }

        public Criteria andBz2NotEqualTo(String value) {
            addCriterion("bz2 <>", value, "bz2");
            return (Criteria) this;
        }

        public Criteria andBz2GreaterThan(String value) {
            addCriterion("bz2 >", value, "bz2");
            return (Criteria) this;
        }

        public Criteria andBz2GreaterThanOrEqualTo(String value) {
            addCriterion("bz2 >=", value, "bz2");
            return (Criteria) this;
        }

        public Criteria andBz2LessThan(String value) {
            addCriterion("bz2 <", value, "bz2");
            return (Criteria) this;
        }

        public Criteria andBz2LessThanOrEqualTo(String value) {
            addCriterion("bz2 <=", value, "bz2");
            return (Criteria) this;
        }

        public Criteria andBz2Like(String value) {
            addCriterion("bz2 like", value, "bz2");
            return (Criteria) this;
        }

        public Criteria andBz2NotLike(String value) {
            addCriterion("bz2 not like", value, "bz2");
            return (Criteria) this;
        }

        public Criteria andBz2In(List<String> values) {
            addCriterion("bz2 in", values, "bz2");
            return (Criteria) this;
        }

        public Criteria andBz2NotIn(List<String> values) {
            addCriterion("bz2 not in", values, "bz2");
            return (Criteria) this;
        }

        public Criteria andBz2Between(String value1, String value2) {
            addCriterion("bz2 between", value1, value2, "bz2");
            return (Criteria) this;
        }

        public Criteria andBz2NotBetween(String value1, String value2) {
            addCriterion("bz2 not between", value1, value2, "bz2");
            return (Criteria) this;
        }

        public Criteria andBz3IsNull() {
            addCriterion("bz3 is null");
            return (Criteria) this;
        }

        public Criteria andBz3IsNotNull() {
            addCriterion("bz3 is not null");
            return (Criteria) this;
        }

        public Criteria andBz3EqualTo(String value) {
            addCriterion("bz3 =", value, "bz3");
            return (Criteria) this;
        }

        public Criteria andBz3NotEqualTo(String value) {
            addCriterion("bz3 <>", value, "bz3");
            return (Criteria) this;
        }

        public Criteria andBz3GreaterThan(String value) {
            addCriterion("bz3 >", value, "bz3");
            return (Criteria) this;
        }

        public Criteria andBz3GreaterThanOrEqualTo(String value) {
            addCriterion("bz3 >=", value, "bz3");
            return (Criteria) this;
        }

        public Criteria andBz3LessThan(String value) {
            addCriterion("bz3 <", value, "bz3");
            return (Criteria) this;
        }

        public Criteria andBz3LessThanOrEqualTo(String value) {
            addCriterion("bz3 <=", value, "bz3");
            return (Criteria) this;
        }

        public Criteria andBz3Like(String value) {
            addCriterion("bz3 like", value, "bz3");
            return (Criteria) this;
        }

        public Criteria andBz3NotLike(String value) {
            addCriterion("bz3 not like", value, "bz3");
            return (Criteria) this;
        }

        public Criteria andBz3In(List<String> values) {
            addCriterion("bz3 in", values, "bz3");
            return (Criteria) this;
        }

        public Criteria andBz3NotIn(List<String> values) {
            addCriterion("bz3 not in", values, "bz3");
            return (Criteria) this;
        }

        public Criteria andBz3Between(String value1, String value2) {
            addCriterion("bz3 between", value1, value2, "bz3");
            return (Criteria) this;
        }

        public Criteria andBz3NotBetween(String value1, String value2) {
            addCriterion("bz3 not between", value1, value2, "bz3");
            return (Criteria) this;
        }

        public Criteria andBz4IsNull() {
            addCriterion("bz4 is null");
            return (Criteria) this;
        }

        public Criteria andBz4IsNotNull() {
            addCriterion("bz4 is not null");
            return (Criteria) this;
        }

        public Criteria andBz4EqualTo(String value) {
            addCriterion("bz4 =", value, "bz4");
            return (Criteria) this;
        }

        public Criteria andBz4NotEqualTo(String value) {
            addCriterion("bz4 <>", value, "bz4");
            return (Criteria) this;
        }

        public Criteria andBz4GreaterThan(String value) {
            addCriterion("bz4 >", value, "bz4");
            return (Criteria) this;
        }

        public Criteria andBz4GreaterThanOrEqualTo(String value) {
            addCriterion("bz4 >=", value, "bz4");
            return (Criteria) this;
        }

        public Criteria andBz4LessThan(String value) {
            addCriterion("bz4 <", value, "bz4");
            return (Criteria) this;
        }

        public Criteria andBz4LessThanOrEqualTo(String value) {
            addCriterion("bz4 <=", value, "bz4");
            return (Criteria) this;
        }

        public Criteria andBz4Like(String value) {
            addCriterion("bz4 like", value, "bz4");
            return (Criteria) this;
        }

        public Criteria andBz4NotLike(String value) {
            addCriterion("bz4 not like", value, "bz4");
            return (Criteria) this;
        }

        public Criteria andBz4In(List<String> values) {
            addCriterion("bz4 in", values, "bz4");
            return (Criteria) this;
        }

        public Criteria andBz4NotIn(List<String> values) {
            addCriterion("bz4 not in", values, "bz4");
            return (Criteria) this;
        }

        public Criteria andBz4Between(String value1, String value2) {
            addCriterion("bz4 between", value1, value2, "bz4");
            return (Criteria) this;
        }

        public Criteria andBz4NotBetween(String value1, String value2) {
            addCriterion("bz4 not between", value1, value2, "bz4");
            return (Criteria) this;
        }

        public Criteria andBz5IsNull() {
            addCriterion("bz5 is null");
            return (Criteria) this;
        }

        public Criteria andBz5IsNotNull() {
            addCriterion("bz5 is not null");
            return (Criteria) this;
        }

        public Criteria andBz5EqualTo(String value) {
            addCriterion("bz5 =", value, "bz5");
            return (Criteria) this;
        }

        public Criteria andBz5NotEqualTo(String value) {
            addCriterion("bz5 <>", value, "bz5");
            return (Criteria) this;
        }

        public Criteria andBz5GreaterThan(String value) {
            addCriterion("bz5 >", value, "bz5");
            return (Criteria) this;
        }

        public Criteria andBz5GreaterThanOrEqualTo(String value) {
            addCriterion("bz5 >=", value, "bz5");
            return (Criteria) this;
        }

        public Criteria andBz5LessThan(String value) {
            addCriterion("bz5 <", value, "bz5");
            return (Criteria) this;
        }

        public Criteria andBz5LessThanOrEqualTo(String value) {
            addCriterion("bz5 <=", value, "bz5");
            return (Criteria) this;
        }

        public Criteria andBz5Like(String value) {
            addCriterion("bz5 like", value, "bz5");
            return (Criteria) this;
        }

        public Criteria andBz5NotLike(String value) {
            addCriterion("bz5 not like", value, "bz5");
            return (Criteria) this;
        }

        public Criteria andBz5In(List<String> values) {
            addCriterion("bz5 in", values, "bz5");
            return (Criteria) this;
        }

        public Criteria andBz5NotIn(List<String> values) {
            addCriterion("bz5 not in", values, "bz5");
            return (Criteria) this;
        }

        public Criteria andBz5Between(String value1, String value2) {
            addCriterion("bz5 between", value1, value2, "bz5");
            return (Criteria) this;
        }

        public Criteria andBz5NotBetween(String value1, String value2) {
            addCriterion("bz5 not between", value1, value2, "bz5");
            return (Criteria) this;
        }

        public Criteria andRoomoruserIsNull() {
            addCriterion("roomoruser is null");
            return (Criteria) this;
        }

        public Criteria andRoomoruserIsNotNull() {
            addCriterion("roomoruser is not null");
            return (Criteria) this;
        }

        public Criteria andRoomoruserEqualTo(Integer value) {
            addCriterion("roomoruser =", value, "roomoruser");
            return (Criteria) this;
        }

        public Criteria andRoomoruserNotEqualTo(Integer value) {
            addCriterion("roomoruser <>", value, "roomoruser");
            return (Criteria) this;
        }

        public Criteria andRoomoruserGreaterThan(Integer value) {
            addCriterion("roomoruser >", value, "roomoruser");
            return (Criteria) this;
        }

        public Criteria andRoomoruserGreaterThanOrEqualTo(Integer value) {
            addCriterion("roomoruser >=", value, "roomoruser");
            return (Criteria) this;
        }

        public Criteria andRoomoruserLessThan(Integer value) {
            addCriterion("roomoruser <", value, "roomoruser");
            return (Criteria) this;
        }

        public Criteria andRoomoruserLessThanOrEqualTo(Integer value) {
            addCriterion("roomoruser <=", value, "roomoruser");
            return (Criteria) this;
        }

        public Criteria andRoomoruserIn(List<Integer> values) {
            addCriterion("roomoruser in", values, "roomoruser");
            return (Criteria) this;
        }

        public Criteria andRoomoruserNotIn(List<Integer> values) {
            addCriterion("roomoruser not in", values, "roomoruser");
            return (Criteria) this;
        }

        public Criteria andRoomoruserBetween(Integer value1, Integer value2) {
            addCriterion("roomoruser between", value1, value2, "roomoruser");
            return (Criteria) this;
        }

        public Criteria andRoomoruserNotBetween(Integer value1, Integer value2) {
            addCriterion("roomoruser not between", value1, value2, "roomoruser");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dlSpaceManager
     *
     * @mbggenerated do_not_delete_during_merge Mon Jul 27 11:25:13 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dlSpaceManager
     *
     * @mbggenerated Mon Jul 27 11:25:13 CST 2015
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}