package com.hndl.mobileplatform.model;

public class OfmucaffiliationKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ofMucAffiliation.roomID
     *
     * @mbggenerated Wed Aug 05 09:24:46 CST 2015
     */
    private Integer roomid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ofMucAffiliation.jid
     *
     * @mbggenerated Wed Aug 05 09:24:46 CST 2015
     */
    private String jid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ofMucAffiliation.roomID
     *
     * @return the value of ofMucAffiliation.roomID
     *
     * @mbggenerated Wed Aug 05 09:24:46 CST 2015
     */
    public Integer getRoomid() {
        return roomid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ofMucAffiliation.roomID
     *
     * @param roomid the value for ofMucAffiliation.roomID
     *
     * @mbggenerated Wed Aug 05 09:24:46 CST 2015
     */
    public void setRoomid(Integer roomid) {
        this.roomid = roomid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ofMucAffiliation.jid
     *
     * @return the value of ofMucAffiliation.jid
     *
     * @mbggenerated Wed Aug 05 09:24:46 CST 2015
     */
    public String getJid() {
        return jid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ofMucAffiliation.jid
     *
     * @param jid the value for ofMucAffiliation.jid
     *
     * @mbggenerated Wed Aug 05 09:24:46 CST 2015
     */
    public void setJid(String jid) {
        this.jid = jid;
    }
}