package com.hndl.mobileplatform.model;

public class Ofmucaffiliation extends OfmucaffiliationKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ofMucAffiliation.affiliation
     *
     * @mbggenerated Wed Aug 05 09:24:46 CST 2015
     */
    private Integer affiliation;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ofMucAffiliation.affiliation
     *
     * @return the value of ofMucAffiliation.affiliation
     *
     * @mbggenerated Wed Aug 05 09:24:46 CST 2015
     */
    public Integer getAffiliation() {
        return affiliation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ofMucAffiliation.affiliation
     *
     * @param affiliation the value for ofMucAffiliation.affiliation
     *
     * @mbggenerated Wed Aug 05 09:24:46 CST 2015
     */
    public void setAffiliation(Integer affiliation) {
        this.affiliation = affiliation;
    }
}