package com.hndl.mobileplatform.dao;

import com.hndl.mobileplatform.model.Dlnoticeperson;
import com.hndl.mobileplatform.model.DlnoticepersonExample;
import com.pmcc.soft.core.common.BaseVO;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface DlnoticepersonMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dlNoticePerson
     *
     * @mbggenerated Wed Jul 22 10:18:43 CST 2015
     */
    int countByExample(DlnoticepersonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dlNoticePerson
     *
     * @mbggenerated Wed Jul 22 10:18:43 CST 2015
     */
    int deleteByExample(DlnoticepersonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dlNoticePerson
     *
     * @mbggenerated Wed Jul 22 10:18:43 CST 2015
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dlNoticePerson
     *
     * @mbggenerated Wed Jul 22 10:18:43 CST 2015
     */
    int insert(Dlnoticeperson record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dlNoticePerson
     *
     * @mbggenerated Wed Jul 22 10:18:43 CST 2015
     */
    int insertSelective(Dlnoticeperson record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dlNoticePerson
     *
     * @mbggenerated Wed Jul 22 10:18:43 CST 2015
     */
    List<Dlnoticeperson> selectByExample(DlnoticepersonExample example);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dlNoticePerson
     *
     * @mbggenerated Wed Jul 22 10:18:43 CST 2015
     */
    Dlnoticeperson selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dlNoticePerson
     *
     * @mbggenerated Wed Jul 22 10:18:43 CST 2015
     */
    int updateByExampleSelective(@Param("record") Dlnoticeperson record, @Param("example") DlnoticepersonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dlNoticePerson
     *
     * @mbggenerated Wed Jul 22 10:18:43 CST 2015
     */
    int updateByExample(@Param("record") Dlnoticeperson record, @Param("example") DlnoticepersonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dlNoticePerson
     *
     * @mbggenerated Wed Jul 22 10:18:43 CST 2015
     */
    int updateByPrimaryKeySelective(Dlnoticeperson record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dlNoticePerson
     *
     * @mbggenerated Wed Jul 22 10:18:43 CST 2015
     */
    int updateByPrimaryKey(Dlnoticeperson record);
}