package com.hndl.mobileplatform.dao;

import com.hndl.mobileplatform.model.Dlnoticemanage;
import com.hndl.mobileplatform.model.DlnoticemanageExample;
import com.hndl.mobileplatform.model.DlroomnoticemessageWithBLOBs;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DlnoticemanageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dlNoticeManage
     *
     * @mbggenerated Thu Jul 16 17:55:50 CST 2015
     */
    int countByExample(DlnoticemanageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dlNoticeManage
     *
     * @mbggenerated Thu Jul 16 17:55:50 CST 2015
     */
    int deleteByExample(DlnoticemanageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dlNoticeManage
     *
     * @mbggenerated Thu Jul 16 17:55:50 CST 2015
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dlNoticeManage
     *
     * @mbggenerated Thu Jul 16 17:55:50 CST 2015
     */
    int insert(Dlnoticemanage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dlNoticeManage
     *
     * @mbggenerated Thu Jul 16 17:55:50 CST 2015
     */
    int insertSelective(Dlnoticemanage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dlNoticeManage
     *
     * @mbggenerated Thu Jul 16 17:55:50 CST 2015
     */
    List<Dlnoticemanage> selectByExampleWithBLOBs(DlnoticemanageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dlNoticeManage
     *
     * @mbggenerated Thu Jul 16 17:55:50 CST 2015
     */
    List<Dlnoticemanage> selectByExample(DlnoticemanageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dlNoticeManage
     *
     * @mbggenerated Thu Jul 16 17:55:50 CST 2015
     */
    Dlnoticemanage selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dlNoticeManage
     *
     * @mbggenerated Thu Jul 16 17:55:50 CST 2015
     */
    int updateByExampleSelective(@Param("record") Dlnoticemanage record, @Param("example") DlnoticemanageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dlNoticeManage
     *
     * @mbggenerated Thu Jul 16 17:55:50 CST 2015
     */
    int updateByExampleWithBLOBs(@Param("record") Dlnoticemanage record, @Param("example") DlnoticemanageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dlNoticeManage
     *
     * @mbggenerated Thu Jul 16 17:55:50 CST 2015
     */
    int updateByExample(@Param("record") Dlnoticemanage record, @Param("example") DlnoticemanageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dlNoticeManage
     *
     * @mbggenerated Thu Jul 16 17:55:50 CST 2015
     */
    int updateByPrimaryKeySelective(Dlnoticemanage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dlNoticeManage
     *
     * @mbggenerated Thu Jul 16 17:55:50 CST 2015
     */
    int updateByPrimaryKeyWithBLOBs(DlroomnoticemessageWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dlNoticeManage
     *
     * @mbggenerated Thu Jul 16 17:55:50 CST 2015
     */
    int updateByPrimaryKey(Dlnoticemanage record);
}