package com.hndl.mobileplatform.dao;

import com.hndl.mobileplatform.model.Dlroomnotice;
import com.hndl.mobileplatform.model.DlroomnoticeExample;
import com.hndl.mobileplatform.model.DlroomnoticeWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DlroomnoticeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dlRoomNotice
     *
     * @mbggenerated Thu Jul 09 16:21:19 CST 2015
     */
    int countByExample(DlroomnoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dlRoomNotice
     *
     * @mbggenerated Thu Jul 09 16:21:19 CST 2015
     */
    int deleteByExample(DlroomnoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dlRoomNotice
     *
     * @mbggenerated Thu Jul 09 16:21:19 CST 2015
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dlRoomNotice
     *
     * @mbggenerated Thu Jul 09 16:21:19 CST 2015
     */
    int insert(DlroomnoticeWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dlRoomNotice
     *
     * @mbggenerated Thu Jul 09 16:21:19 CST 2015
     */
    int insertSelective(DlroomnoticeWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dlRoomNotice
     *
     * @mbggenerated Thu Jul 09 16:21:19 CST 2015
     */
    List<DlroomnoticeWithBLOBs> selectByExampleWithBLOBs(DlroomnoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dlRoomNotice
     *
     * @mbggenerated Thu Jul 09 16:21:19 CST 2015
     */
    List<Dlroomnotice> selectByExample(DlroomnoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dlRoomNotice
     *
     * @mbggenerated Thu Jul 09 16:21:19 CST 2015
     */
    DlroomnoticeWithBLOBs selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dlRoomNotice
     *
     * @mbggenerated Thu Jul 09 16:21:19 CST 2015
     */
    int updateByExampleSelective(@Param("record") DlroomnoticeWithBLOBs record, @Param("example") DlroomnoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dlRoomNotice
     *
     * @mbggenerated Thu Jul 09 16:21:19 CST 2015
     */
    int updateByExampleWithBLOBs(@Param("record") DlroomnoticeWithBLOBs record, @Param("example") DlroomnoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dlRoomNotice
     *
     * @mbggenerated Thu Jul 09 16:21:19 CST 2015
     */
    int updateByExample(@Param("record") Dlroomnotice record, @Param("example") DlroomnoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dlRoomNotice
     *
     * @mbggenerated Thu Jul 09 16:21:19 CST 2015
     */
    int updateByPrimaryKeySelective(DlroomnoticeWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dlRoomNotice
     *
     * @mbggenerated Thu Jul 09 16:21:19 CST 2015
     */
    int updateByPrimaryKeyWithBLOBs(DlroomnoticeWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dlRoomNotice
     *
     * @mbggenerated Thu Jul 09 16:21:19 CST 2015
     */
    int updateByPrimaryKey(Dlroomnotice record);
}