package com.hndl.mobileplatform.dao;

import com.hndl.mobileplatform.model.Dlroompost;
import com.hndl.mobileplatform.model.DlroompostExample;
import com.hndl.mobileplatform.model.DlroompostWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DlroompostMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dlRoomPost
     *
     * @mbggenerated Thu Jul 16 17:57:16 CST 2015
     */
    int countByExample(DlroompostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dlRoomPost
     *
     * @mbggenerated Thu Jul 16 17:57:16 CST 2015
     */
    int deleteByExample(DlroompostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dlRoomPost
     *
     * @mbggenerated Thu Jul 16 17:57:16 CST 2015
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dlRoomPost
     *
     * @mbggenerated Thu Jul 16 17:57:16 CST 2015
     */
    int insert(DlroompostWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dlRoomPost
     *
     * @mbggenerated Thu Jul 16 17:57:16 CST 2015
     */
    int insertSelective(DlroompostWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dlRoomPost
     *
     * @mbggenerated Thu Jul 16 17:57:16 CST 2015
     */
    List<DlroompostWithBLOBs> selectByExampleWithBLOBs(DlroompostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dlRoomPost
     *
     * @mbggenerated Thu Jul 16 17:57:16 CST 2015
     */
    List<Dlroompost> selectByExample(DlroompostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dlRoomPost
     *
     * @mbggenerated Thu Jul 16 17:57:16 CST 2015
     */
    DlroompostWithBLOBs selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dlRoomPost
     *
     * @mbggenerated Thu Jul 16 17:57:16 CST 2015
     */
    int updateByExampleSelective(@Param("record") DlroompostWithBLOBs record, @Param("example") DlroompostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dlRoomPost
     *
     * @mbggenerated Thu Jul 16 17:57:16 CST 2015
     */
    int updateByExampleWithBLOBs(@Param("record") DlroompostWithBLOBs record, @Param("example") DlroompostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dlRoomPost
     *
     * @mbggenerated Thu Jul 16 17:57:16 CST 2015
     */
    int updateByExample(@Param("record") Dlroompost record, @Param("example") DlroompostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dlRoomPost
     *
     * @mbggenerated Thu Jul 16 17:57:16 CST 2015
     */
    int updateByPrimaryKeySelective(DlroompostWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dlRoomPost
     *
     * @mbggenerated Thu Jul 16 17:57:16 CST 2015
     */
    int updateByPrimaryKeyWithBLOBs(DlroompostWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dlRoomPost
     *
     * @mbggenerated Thu Jul 16 17:57:16 CST 2015
     */
    int updateByPrimaryKey(Dlroompost record);
}