package com.hndl.mobileplatform.dao;

import com.hndl.mobileplatform.model.Dlroomaffiche;
import com.hndl.mobileplatform.model.DlroomafficheExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DlroomafficheMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dlRoomAffiche
     *
     * @mbggenerated Thu Jul 16 17:53:57 CST 2015
     */
    int countByExample(DlroomafficheExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dlRoomAffiche
     *
     * @mbggenerated Thu Jul 16 17:53:57 CST 2015
     */
    int deleteByExample(DlroomafficheExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dlRoomAffiche
     *
     * @mbggenerated Thu Jul 16 17:53:57 CST 2015
     */
    int deleteByPrimaryKey(String afficheid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dlRoomAffiche
     *
     * @mbggenerated Thu Jul 16 17:53:57 CST 2015
     */
    int insert(Dlroomaffiche record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dlRoomAffiche
     *
     * @mbggenerated Thu Jul 16 17:53:57 CST 2015
     */
    int insertSelective(Dlroomaffiche record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dlRoomAffiche
     *
     * @mbggenerated Thu Jul 16 17:53:57 CST 2015
     */
    List<Dlroomaffiche> selectByExampleWithBLOBs(DlroomafficheExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dlRoomAffiche
     *
     * @mbggenerated Thu Jul 16 17:53:57 CST 2015
     */
    List<Dlroomaffiche> selectByExample(DlroomafficheExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dlRoomAffiche
     *
     * @mbggenerated Thu Jul 16 17:53:57 CST 2015
     */
    Dlroomaffiche selectByPrimaryKey(String afficheid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dlRoomAffiche
     *
     * @mbggenerated Thu Jul 16 17:53:57 CST 2015
     */
    int updateByExampleSelective(@Param("record") Dlroomaffiche record, @Param("example") DlroomafficheExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dlRoomAffiche
     *
     * @mbggenerated Thu Jul 16 17:53:57 CST 2015
     */
    int updateByExampleWithBLOBs(@Param("record") Dlroomaffiche record, @Param("example") DlroomafficheExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dlRoomAffiche
     *
     * @mbggenerated Thu Jul 16 17:53:57 CST 2015
     */
    int updateByExample(@Param("record") Dlroomaffiche record, @Param("example") DlroomafficheExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dlRoomAffiche
     *
     * @mbggenerated Thu Jul 16 17:53:57 CST 2015
     */
    int updateByPrimaryKeySelective(Dlroomaffiche record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dlRoomAffiche
     *
     * @mbggenerated Thu Jul 16 17:53:57 CST 2015
     */
    int updateByPrimaryKeyWithBLOBs(Dlroomaffiche record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dlRoomAffiche
     *
     * @mbggenerated Thu Jul 16 17:53:57 CST 2015
     */
    int updateByPrimaryKey(Dlroomaffiche record);
}