package com.hndl.mobileplatform.dao;

import com.hndl.mobileplatform.model.Dlsoftversion;
import com.hndl.mobileplatform.model.DlsoftversionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DlsoftversionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dlSoftVersion
     *
     * @mbggenerated Thu Jul 02 08:48:19 CST 2015
     */
    int countByExample(DlsoftversionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dlSoftVersion
     *
     * @mbggenerated Thu Jul 02 08:48:19 CST 2015
     */
    int deleteByExample(DlsoftversionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dlSoftVersion
     *
     * @mbggenerated Thu Jul 02 08:48:19 CST 2015
     */
    int deleteByPrimaryKey(String versionid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dlSoftVersion
     *
     * @mbggenerated Thu Jul 02 08:48:19 CST 2015
     */
    int insert(Dlsoftversion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dlSoftVersion
     *
     * @mbggenerated Thu Jul 02 08:48:19 CST 2015
     */
    int insertSelective(Dlsoftversion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dlSoftVersion
     *
     * @mbggenerated Thu Jul 02 08:48:19 CST 2015
     */
    List<Dlsoftversion> selectByExample(DlsoftversionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dlSoftVersion
     *
     * @mbggenerated Thu Jul 02 08:48:19 CST 2015
     */
    Dlsoftversion selectByPrimaryKey(String versionid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dlSoftVersion
     *
     * @mbggenerated Thu Jul 02 08:48:19 CST 2015
     */
    int updateByExampleSelective(@Param("record") Dlsoftversion record, @Param("example") DlsoftversionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dlSoftVersion
     *
     * @mbggenerated Thu Jul 02 08:48:19 CST 2015
     */
    int updateByExample(@Param("record") Dlsoftversion record, @Param("example") DlsoftversionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dlSoftVersion
     *
     * @mbggenerated Thu Jul 02 08:48:19 CST 2015
     */
    int updateByPrimaryKeySelective(Dlsoftversion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dlSoftVersion
     *
     * @mbggenerated Thu Jul 02 08:48:19 CST 2015
     */
    int updateByPrimaryKey(Dlsoftversion record);
}