package com.hndl.mobileplatform.dao;

import com.hndl.mobileplatform.model.Dlspacemanager;
import com.hndl.mobileplatform.model.DlspacemanagerExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DlspacemanagerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dlSpaceManager
     *
     * @mbggenerated Mon Jul 27 11:25:13 CST 2015
     */
    int countByExample(DlspacemanagerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dlSpaceManager
     *
     * @mbggenerated Mon Jul 27 11:25:13 CST 2015
     */
    int deleteByExample(DlspacemanagerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dlSpaceManager
     *
     * @mbggenerated Mon Jul 27 11:25:13 CST 2015
     */
    int deleteByPrimaryKey(String spaceid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dlSpaceManager
     *
     * @mbggenerated Mon Jul 27 11:25:13 CST 2015
     */
    int insert(Dlspacemanager record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dlSpaceManager
     *
     * @mbggenerated Mon Jul 27 11:25:13 CST 2015
     */
    int insertSelective(Dlspacemanager record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dlSpaceManager
     *
     * @mbggenerated Mon Jul 27 11:25:13 CST 2015
     */
    List<Dlspacemanager> selectByExample(DlspacemanagerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dlSpaceManager
     *
     * @mbggenerated Mon Jul 27 11:25:13 CST 2015
     */
    Dlspacemanager selectByPrimaryKey(String spaceid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dlSpaceManager
     *
     * @mbggenerated Mon Jul 27 11:25:13 CST 2015
     */
    int updateByExampleSelective(@Param("record") Dlspacemanager record, @Param("example") DlspacemanagerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dlSpaceManager
     *
     * @mbggenerated Mon Jul 27 11:25:13 CST 2015
     */
    int updateByExample(@Param("record") Dlspacemanager record, @Param("example") DlspacemanagerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dlSpaceManager
     *
     * @mbggenerated Mon Jul 27 11:25:13 CST 2015
     */
    int updateByPrimaryKeySelective(Dlspacemanager record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dlSpaceManager
     *
     * @mbggenerated Mon Jul 27 11:25:13 CST 2015
     */
    int updateByPrimaryKey(Dlspacemanager record);
}