package com.hndl.mobileplatform.dao;

import com.hndl.mobileplatform.model.Dlwechatmanager;
import com.hndl.mobileplatform.model.DlwechatmanagerExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DlwechatmanagerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dlWeChatManager
     *
     * @mbggenerated Wed Oct 21 08:58:28 CST 2015
     */
    int countByExample(DlwechatmanagerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dlWeChatManager
     *
     * @mbggenerated Wed Oct 21 08:58:28 CST 2015
     */
    int deleteByExample(DlwechatmanagerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dlWeChatManager
     *
     * @mbggenerated Wed Oct 21 08:58:28 CST 2015
     */
    int deleteByPrimaryKey(String oid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dlWeChatManager
     *
     * @mbggenerated Wed Oct 21 08:58:28 CST 2015
     */
    int insert(Dlwechatmanager record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dlWeChatManager
     *
     * @mbggenerated Wed Oct 21 08:58:28 CST 2015
     */
    int insertSelective(Dlwechatmanager record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dlWeChatManager
     *
     * @mbggenerated Wed Oct 21 08:58:28 CST 2015
     */
    List<Dlwechatmanager> selectByExample(DlwechatmanagerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dlWeChatManager
     *
     * @mbggenerated Wed Oct 21 08:58:28 CST 2015
     */
    Dlwechatmanager selectByPrimaryKey(String oid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dlWeChatManager
     *
     * @mbggenerated Wed Oct 21 08:58:28 CST 2015
     */
    int updateByExampleSelective(@Param("record") Dlwechatmanager record, @Param("example") DlwechatmanagerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dlWeChatManager
     *
     * @mbggenerated Wed Oct 21 08:58:28 CST 2015
     */
    int updateByExample(@Param("record") Dlwechatmanager record, @Param("example") DlwechatmanagerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dlWeChatManager
     *
     * @mbggenerated Wed Oct 21 08:58:28 CST 2015
     */
    int updateByPrimaryKeySelective(Dlwechatmanager record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dlWeChatManager
     *
     * @mbggenerated Wed Oct 21 08:58:28 CST 2015
     */
    int updateByPrimaryKey(Dlwechatmanager record);
}