package com.hndl.mobileplatform.dao;

import com.hndl.mobileplatform.model.Ofmucaffiliation;
import com.hndl.mobileplatform.model.OfmucaffiliationExample;
import com.hndl.mobileplatform.model.OfmucaffiliationKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OfmucaffiliationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ofMucAffiliation
     *
     * @mbggenerated Wed Aug 05 09:24:46 CST 2015
     */
    int countByExample(OfmucaffiliationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ofMucAffiliation
     *
     * @mbggenerated Wed Aug 05 09:24:46 CST 2015
     */
    int deleteByExample(OfmucaffiliationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ofMucAffiliation
     *
     * @mbggenerated Wed Aug 05 09:24:46 CST 2015
     */
    int deleteByPrimaryKey(OfmucaffiliationKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ofMucAffiliation
     *
     * @mbggenerated Wed Aug 05 09:24:46 CST 2015
     */
    int insert(Ofmucaffiliation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ofMucAffiliation
     *
     * @mbggenerated Wed Aug 05 09:24:46 CST 2015
     */
    int insertSelective(Ofmucaffiliation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ofMucAffiliation
     *
     * @mbggenerated Wed Aug 05 09:24:46 CST 2015
     */
    List<Ofmucaffiliation> selectByExample(OfmucaffiliationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ofMucAffiliation
     *
     * @mbggenerated Wed Aug 05 09:24:46 CST 2015
     */
    Ofmucaffiliation selectByPrimaryKey(OfmucaffiliationKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ofMucAffiliation
     *
     * @mbggenerated Wed Aug 05 09:24:46 CST 2015
     */
    int updateByExampleSelective(@Param("record") Ofmucaffiliation record, @Param("example") OfmucaffiliationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ofMucAffiliation
     *
     * @mbggenerated Wed Aug 05 09:24:46 CST 2015
     */
    int updateByExample(@Param("record") Ofmucaffiliation record, @Param("example") OfmucaffiliationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ofMucAffiliation
     *
     * @mbggenerated Wed Aug 05 09:24:46 CST 2015
     */
    int updateByPrimaryKeySelective(Ofmucaffiliation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ofMucAffiliation
     *
     * @mbggenerated Wed Aug 05 09:24:46 CST 2015
     */
    int updateByPrimaryKey(Ofmucaffiliation record);
}